### PACOTES

In [3]:
import pandas as pd
import numpy as np
import itertools
from sklearn.preprocessing import StandardScaler
from sklearn.mixture import GaussianMixture
from sklearn.metrics import silhouette_score, davies_bouldin_score, calinski_harabasz_score
from scipy.spatial.distance import euclidean
from sklearn.preprocessing import RobustScaler

import time

In [4]:

inicio = time.time()
df_resumo = pd.read_csv('resumo_features.csv')
df = pd.read_csv('creditcard.csv')

# AJUSTE DE TIPOS
df_resumo['Comparacao_dis_whith'] = pd.to_numeric(
    df_resumo['Comparacao_dis_whith'],
    errors='coerce'
)

# MANN-WHITNEY SCORE
# Quanto menor o p-value -> melhor
df_resumo['MannWhitney_Score'] = -np.log10(
    df_resumo['Comparacao_dis_whith'] + 1e-300
)

# CORRELAÇÃO ABSOLUTA
df_resumo['Corr_spearman_abs'] = abs(
    df_resumo['Correlacao_spearman']
)

# AJUSTE DE MÉTRICAS DISTRIBUCIONAIS

# KL e Wasser podem explodir
# Aplicamos log para estabilizar

df_resumo['divergencia_kl'] = np.log1p(
    abs(df_resumo['divergencia_kl'])
)

df_resumo['Wasser'] = np.log1p(
    abs(df_resumo['Wasser'])
)

# AJUSTE DE NORMALIDADE

# Quanto MENOR distância da normalidade -> melhor
df_resumo['Normalidade_Score'] = 1 / (
    1 + abs(df_resumo['Normalidade'])
)

# AJUSTE DE ASSIMETRIA
df_resumo['Skewness_Score'] = 1 / (
    1 + abs(df_resumo['Assimetria'])
)


# AJUSTE DE CURTOSE
df_resumo['Kurtosis_Score'] = 1 / (
    1 + abs(df_resumo['Curtose'])
)

# AJUSTE DE OUTLIERS
df_resumo['Outlier_Score'] = 1 / (
    1 + df_resumo['Qnd_Outliers']
)

# MÉTRICAS UTILIZADAS
metricas = [

    # INDISPENSÁVEL
    'Curva ROC',
    'KS',

    # MUITO IMPORTANTE
    'divergencia_kl',
    'Wasser',

    # IMPORTANTE
    'inf_mutua',
    'MannWhitney_Score',

    # BOM
    'Normalidade_Score',
    'Sep_mediana_norm',

    # ÚTIL
    'Skewness_Score',
    'Kurtosis_Score',

    # ACESSÓRIO
    'Corr_spearman_abs',
    'Outlier_Score'
]


# TRATAMENTO DE NaN
df_resumo[metricas] = df_resumo[
    metricas
].fillna(0)


# NORMALIZAÇÃO ROBUSTA
# Melhor para fraude/outliers

scaler = RobustScaler()

df_norm = df_resumo.copy()

df_norm[metricas] = scaler.fit_transform(
    df_norm[metricas]
)


# MIN-MAX FINAL
# Após robust scaling

for col in metricas:

    minimo = df_norm[col].min()
    maximo = df_norm[col].max()

    df_norm[col] = (
        (df_norm[col] - minimo)
        /
        (maximo - minimo + 1e-9)
    )


# SCORE FINAL
df_norm['Score_Final'] = (

    # INDISPENSÁVEL -> 0.25
    df_norm['Curva ROC'] * 0.125 +
    df_norm['KS'] * 0.125 +

    # MUITO IMPORTANTE -> 0.21
    df_norm['divergencia_kl'] * 0.105 +
    df_norm['Wasser'] * 0.105 +

    # IMPORTANTE -> 0.17
    df_norm['inf_mutua'] * 0.085 +
    df_norm['MannWhitney_Score'] * 0.085 +

    # BOM -> 0.13
    df_norm['Normalidade_Score'] * 0.065 +
    df_norm['Sep_mediana_norm'] * 0.065 +

    # ÚTIL -> 0.09
    df_norm['Skewness_Score'] * 0.045 +
    df_norm['Kurtosis_Score'] * 0.045 +

    # ACESSÓRIO -> 0.05
    df_norm['Corr_spearman_abs'] * 0.025 +
    df_norm['Outlier_Score'] * 0.025
)


# GARANTIR SEM NaN
df_norm['Score_Final'] = df_norm[
    'Score_Final'
].fillna(0)

# RANKING FINAL
ranking = df_norm.sort_values(
    'Score_Final',
    ascending=False
).reset_index(drop=True)

# POSIÇÃO
ranking.insert(
    0,
    'Posicao_Rank',
    ranking.index + 1
)

# EXIBIÇÃO
pd.set_option(
    'display.max_columns',
    None
)

display(ranking)

# SALVAR CSV
ranking.to_csv(
    'individual_score_feature_individuais.csv',
    index=False
)

print('\nCSV salvo com sucesso!')

,Posicao_Rank,Feature,Normalidade,Qnd_Outliers,Sep_mediana_norm,Comparacao_dis_whith,Correlacao_spearman,inf_mutua,divergencia_kl,Curva ROC,KS,Wasser,Assimetria,Curtose,MannWhitney_Score,Corr_spearman_abs,Normalidade_Score,Skewness_Score,Kurtosis_Score,Outlier_Score,Score_Final
0,1,V14,0,14149,1.000000,1.471581e-260,-0.064613,0.984641,1.000000,1.000000,1.000000,0.211410,1.995165,23.879022,1.000000,1.000000,0.0,0.305756,0.046824,0.000045,0.651760
1,2,V12,0,15348,0.796989,8.416027e-247,-0.062870,0.917286,0.840947,0.972118,0.924927,0.201544,2.278389,20.241493,0.946936,0.972125,0.0,0.274060,0.055062,0.000040,0.595970
2,3,V10,0,9496,0.579452,9.611131e-222,-0.059564,0.908347,0.894367,0.919245,0.950893,0.192730,1.187134,31.987656,0.850284,0.919255,0.0,0.441298,0.035000,0.000080,0.579477
3,4,V11,0,780,0.497847,4.910592e-226,0.060143,0.820345,0.725013,0.928507,0.889460,0.157954,0.356504,1.633872,0.866838,0.928514,0.0,0.748947,0.453109,0.001255,0.573065
4,5,V4,0,11148,0.415041,3.625904e-248,0.063045,0.586806,0.805397,0.974920,0.902628,0.173101,0.676289,2.635388,0.952203,0.974924,0.0,0.594410,0.327929,0.000064,0.561109
5,6,V17,0,7420,0.870823,9.219384e-124,-0.044335,1.000000,0.905760,0.675706,0.875582,0.212480,3.844894,94.798034,0.472352,0.675708,0.0,0.165685,0.011212,0.000109,0.517935
6,7,V3,0,3363,0.486416,1.211048e-219,-0.059278,0.583784,0.718940,0.914680,0.822726,0.212220,2.240144,26.619062,0.842183,0.914681,0.0,0.278017,0.042052,0.000272,0.505049
7,8,V16,0,8184,0.580474,1.808172e-156,-0.049936,0.733854,0.745415,0.765280,0.800845,0.165757,1.100960,10.418927,0.598510,0.765281,0.0,0.461906,0.103528,0.000097,0.486999
8,9,V7,0,8948,0.346706,1.464234e-146,-0.048308,0.457887,0.709440,0.739240,0.767815,0.191285,2.553894,405.600275,0.560292,0.739245,0.0,0.248076,0.001663,0.000086,0.421761
9,10,V9,0,8283,0.272512,8.943723e-154,-0.049499,0.498804,0.482208,0.758284,0.660477,0.127076,0.554677,3.731224,0.588117,0.758292,0.0,0.645688,0.251678,0.000095,0.410763
10,11,V2,0,13526,0.221554,1.650438e-163,0.051062,0.366738,0.652029,0.783279,0.732939,0.154597,4.624841,95.771404,0.625663,0.783288,0.0,0.134235,0.011086,0.000048,0.399101
11,12,V18,0,7533,0.274983,2.648962e-77,-0.034872,0.503840,0.449384,0.524375,0.567532,0.118919,0.259879,2.578275,0.293154,0.524372,0.0,0.811075,0.333184,0.000107,0.346382
12,13,V21,0,14497,0.113302,8.673355e-80,0.035442,0.269042,0.658528,0.533488,0.586854,0.087094,3.592972,207.283380,0.302739,0.533488,0.0,0.178125,0.004465,0.000043,0.295854
13,14,V1,0,7062,0.164473,1.740785e-113,-0.042424,0.228125,0.262744,0.645134,0.531826,0.177403,3.280650,32.486088,0.432715,0.645146,0.0,0.195581,0.034460,0.000116,0.286681
14,15,V6,0,22965,0.115800,2.231002e-93,-0.038410,0.260985,0.436498,0.580947,0.545958,0.086852,1.826571,42.641724,0.355156,0.580953,0.0,0.327639,0.026143,0.000018,0.286158
15,16,V27,0,39163,0.131614,1.414589e-51,0.028311,0.268035,0.764981,0.419450,0.524451,0.051909,1.170203,244.984919,0.193919,0.419447,0.0,0.445218,0.003585,0.000000,0.282264
16,17,tempo_desde_a_primeira_transacao,0,0,0.020153,4.386159e-10,-0.011692,0.203450,0.008226,0.153673,0.142081,1.000000,0.035567,1.293528,0.033879,0.153670,0.0,1.000000,0.520538,1.000000,0.261582
17,18,V5,0,12295,0.144326,3.053712e-58,-0.030147,0.261362,0.496302,0.448817,0.482284,0.146007,2.425889,206.900907,0.219630,0.448809,0.0,0.259629,0.004476,0.000056,0.257202
18,19,V19,0,10205,0.105324,2.401960e-33,0.022546,0.145663,0.276783,0.327259,0.352651,0.056357,0.109191,1.724918,0.123603,0.327251,0.0,0.929567,0.437927,0.000072,0.219422
19,20,V28,0,30342,0.051035,1.203683e-27,0.020417,0.195896,0.628205,0.293207,0.395677,0.020084,11.192032,933.381095,0.101617,0.293203,0.0,0.029006,0.000000,0.000007,0.191422
20,21,V8,0,24134,0.064204,8.509891e-34,0.022706,0.199295,0.389259,0.329815,0.395598,0.132442,8.521899,220.583080,0.125341,0.329810,0.0,0.054280,0.004120,0.000016,0.188096
21,22,V20,0,27770,0.056890,1.128104e-30,0.021574,0.112300,0.434619,0.311710,0.389932,0.041662,2.037145,271.011334,0.113297,0.311706,0.0,0.300685,0.003119,0.000010,0.182052
22,23,valor_de_transacao,0,31904,0.000000,8.578472e-06,-0.008339,0.153217,0.407845,0.100041,0.271770,0.399682,16.977635,845.077788,0.017327,0.100048,0.0,0.000000,0.000134,0.000006,0.148270
23,24,V24,0,4774,0.016692,9.423066e-07,-0.009188,0.041168,0.281482,0.113628,0.090875,0.006312,0.552496,0.618839,0.021027,0.113625,0.0,0.646681,0.738018,0.000184,0.127309
24,25,V13,0,3368,0.000184,5.121481e-02,-0.003653,0.011708,0.049715,0.025119,0.057659,0.006128,0.065233,0.195275,0.002762,0.025108,0.0,0.970448,1.000000,0.000271,0.106757
25,26,V26,0,5596,0.009438,3.531905e-03,0.005466,0.023291,0.269617,0.054113,0.041926,0.000000,0.576690,0.918969,0.007242,0.054102,0.0,0.635820,0.622390,0.000153,0.101499
26,27,V15,0,2894,0.009156,1.295082e-01,-0.002841,0.000000,0.107053,0.012126,0.007078,0.004082,0.308421,0.284743,0.001208,0.012122,0.0,0.778717,0.930272,0.000320,0.091983
27,28,V25,0,5367,0.012395,1.246293e-02,0.004682,0.023291,0.210128,0.041573,0.038563,0.011027,0.415790,4.290316,0.005130,0.041564,0.0,0.715026,0.224945,0.000161,0.079801
28,29,V23,0,18541,0.006876,7.419609e-03,-0.005017,0.056276,0.309442,0.046926,0.158070,0.031466,5.875109,440.080912,0.005998,0.046921,0.0,0.098708,0.001432,0.000028,0.072840
29,30,V22,0,1317,0.000923,2.663947e-01,0.002083,0.004784,0.000000,0.000000,0.000000,0.018208,0.213256,2.832896,0.000000,0.000000,0.0,0.844592,0.310965,0.000733,0.054397

CSV salvo com sucesso!

### TOP 10

In [5]:

# CARREGAR CSV DO RANKING
ranking = pd.read_csv('individual_score_feature_individuais.csv')

ranking = ranking.sort_values(
    by='Score_Final',
    ascending=False
)

top10 = ranking.head(10)

# ATRIBUINDO ÀS VARIÁVEIS
Primeiro_lugar = top10.iloc[0]['Feature']
Segundo_lugar = top10.iloc[1]['Feature']
Terceiro_lugar = top10.iloc[2]['Feature']
Quarto_lugar = top10.iloc[3]['Feature']
Quinto_lugar = top10.iloc[4]['Feature']
Sexto_lugar = top10.iloc[5]['Feature']
Setimo_lugar = top10.iloc[6]['Feature']
Oitavo_lugar = top10.iloc[7]['Feature']
Nono_lugar = top10.iloc[8]['Feature']
Decimo_lugar = top10.iloc[9]['Feature']

# PRINT TOP 10
print('TOP 10 FEATURES:\n')

for i, row in top10.iterrows():

    print(
        f"{row['Posicao_Rank']}º -> "
        f"{row['Feature']}"
    )

# LISTA FINAL
features_top10 = top10['Feature'].tolist()
print('\nLista Top 10:\n')
print(features_top10)

TOP 10 FEATURES:

1º -> V14
2º -> V12
3º -> V10
4º -> V11
5º -> V4
6º -> V17
7º -> V3
8º -> V16
9º -> V7
10º -> V9

Lista Top 10:

['V14', 'V12', 'V10', 'V11', 'V4', 'V17', 'V3', 'V16', 'V7', 'V9']

 ### CRIANDO CSV DE COMBINACOES 2X2 E 3X3

In [6]:

# ==================================================
# CONFIG
# ==================================================

RANDOM_STATE = 42

# 5% da população
SAMPLE_PERCENT = 0.05

# FEATURES PCA
features_pca = top10['Feature'].tolist()

# ==================================================
# FUNÇÃO PRINCIPAL
# ==================================================

def calcular_metricas(
    combinacoes,
    dimensao='2D'
):

    resultados = []

    for combo in combinacoes:

        try:

            # =========================
            # DADOS
            # =========================

            X = df[list(combo)].values

            # =========================
            # PADRONIZAÇÃO
            # =========================

            scaler = StandardScaler()

            X_scaled = scaler.fit_transform(X)

            # =========================
            # GMM
            # =========================

            gmm = GaussianMixture(

                n_components=2,
                covariance_type='diag',
                random_state=RANDOM_STATE

            )

            labels = gmm.fit_predict(
                X_scaled
            )

            # =========================
            # AMOSTRA 5%
            # =========================

            sample_size = max(

                100,

                int(
                    len(X_scaled)
                    * SAMPLE_PERCENT
                )

            )

            idx = np.random.choice(

                len(X_scaled),

                size=sample_size,

                replace=False

            )

            X_sample = X_scaled[idx]

            labels_sample = labels[idx]

            # =========================
            # 1. SILHOUETTE
            # =========================

            silhouette = silhouette_score(

                X_sample,
                labels_sample

            )

            # =========================
            # 2. DAVIES-BOULDIN
            # =========================

            davies = davies_bouldin_score(

                X_sample,
                labels_sample

            )

            # =========================
            # 3. CALINSKI-HARABASZ
            # =========================

            calinski = calinski_harabasz_score(

                X_sample,
                labels_sample

            )

            # =========================
            # 4. DISTÂNCIA CENTROIDES
            # =========================

            centro_0 = X_sample[
                labels_sample == 0
            ].mean(axis=0)

            centro_1 = X_sample[
                labels_sample == 1
            ].mean(axis=0)

            centroid_dist = euclidean(

                centro_0,
                centro_1

            )

            # =========================
            # 5. OVERLAP GMM
            # =========================

            probs = gmm.predict_proba(
                X_sample
            )

            overlap = np.mean(

                np.min(probs, axis=1)

            )

            overlap_score = 1 - overlap

            # =========================
            # RESULTADOS
            # =========================

            resultado = {

                'Features': ' | '.join(combo),

                'Silhouette': round(
                    float(silhouette), 6
                ),

                'Davies_Bouldin': round(
                    float(davies), 6
                ),

                'Calinski_Harabasz': round(
                    float(calinski), 6
                ),

                'Dist_Centroides': round(
                    float(centroid_dist), 6
                ),

                'Overlap_GMM': round(
                    float(overlap_score), 6
                )
            }

            resultados.append(resultado)

            # =========================
            # PRINT
            # =========================

            print(

                f'[{dimensao}] '

                f'{" | ".join(combo)} '

                f'| SIL: {silhouette:.4f} '

                f'| DB: {davies:.4f} '

                f'| CH: {calinski:.2f} '

                f'| CENT: {centroid_dist:.4f} '

                f'| OVER: {overlap_score:.4f}'
            )

        except Exception as e:

            print(
                f'Erro em {combo}: {e}'
            )

    return pd.DataFrame(resultados)

# ==================================================
# 2x2
# ==================================================

combinacoes_2d = list(
    itertools.combinations(
        features_pca,
        2
    )
)

print(
    f'\nTotal 2x2: '
    f'{len(combinacoes_2d)}'
)

df_2d = calcular_metricas(

    combinacoes_2d,

    dimensao='2D'

)

# CSV 2D
df_2d.to_csv(

    '2X2_visu_metricas.csv',

    index=False

)

print(
    '\nCSV 2x2 salvo com sucesso!'
)

# ==================================================
# 3x3
# ==================================================

combinacoes_3d = list(
    itertools.combinations(
        features_pca,
        3
    )
)

print(
    f'\nTotal 3x3: '
    f'{len(combinacoes_3d)}'
)

df_3d = calcular_metricas(

    combinacoes_3d,

    dimensao='3D'

)

# CSV 3D
df_3d.to_csv(

    '3X3_visu_metricas.csv',

    index=False

)

print(
    '\nCSV 3x3 salvo com sucesso!'
)

# ==================================================
# DISPLAY
# ==================================================

display(df_2d.head())

display(df_3d.head())
# No final do seu script:
fim = time.time()
tempo_total = fim - inicio

# Convertendo para um formato amigável (minutos e segundos)
minutos = int(tempo_total // 60)
segundos = tempo_total % 60

print(f'\n✓ Processo concluído em: {minutos}m {segundos:.2f}s')

Total 2x2: 45
[2D] V14 | V12 | SIL: 0.5462 | DB: 1.7478 | CH: 2741.18 | CENT: 1.7875 | OVER: 0.9410
[2D] V14 | V10 | SIL: 0.6396 | DB: 2.4924 | CH: 994.40 | CENT: 1.7537 | OVER: 0.9714
[2D] V14 | V11 | SIL: 0.4011 | DB: 4.9997 | CH: 367.22 | CENT: 0.6776 | OVER: 0.8525
[2D] V14 | V4 | SIL: 0.4287 | DB: 3.1998 | CH: 973.99 | CENT: 1.0181 | OVER: 0.8488
[2D] V14 | V17 | SIL: 0.6113 | DB: 1.7162 | CH: 1708.67 | CENT: 2.0215 | OVER: 0.9594
[2D] V14 | V3 | SIL: 0.5198 | DB: 2.0594 | CH: 1693.07 | CENT: 1.6945 | OVER: 0.9199
[2D] V14 | V16 | SIL: 0.4588 | DB: 5.0113 | CH: 378.21 | CENT: 0.7069 | OVER: 0.8727
[2D] V14 | V7 | SIL: 0.6479 | DB: 4.8752 | CH: 302.29 | CENT: 0.9614 | OVER: 0.9709
[2D] V14 | V9 | SIL: 0.4231 | DB: 2.8100 | CH: 1256.67 | CENT: 1.0896 | OVER: 0.8584
[2D] V12 | V10 | SIL: 0.4799 | DB: 1.5813 | CH: 3362.18 | CENT: 1.6101 | OVER: 0.8954
[2D] V12 | V11 | SIL: 0.4608 | DB: 1.2466 | CH: 4083.12 | CENT: 2.0427 | OVER: 0.8754
[2D] V12 | V4 | SIL: 0.4084 | DB: 2.0108 | CH: 2699.93 | CENT: 1.3213 | OVER: 0.8497
[2D] V12 | V17 | SIL: 0.5114 | DB: 1.1984 | CH: 4759.36 | CENT: 2.0057 | OVER: 0.9196
[2D] V12 | V3 | SIL: 0.4897 | DB: 1.3094 | CH: 3732.80 | CENT: 2.0395 | OVER: 0.9000
[2D] V12 | V16 | SIL: 0.4336 | DB: 1.7337 | CH: 2981.14 | CENT: 1.5383 | OVER: 0.8555
[2D] V12 | V7 | SIL: 0.5519 | DB: 1.6254 | CH: 2645.07 | CENT: 1.7584 | OVER: 0.9401
[2D] V12 | V9 | SIL: 0.4705 | DB: 1.7418 | CH: 3260.31 | CENT: 1.5996 | OVER: 0.8787
[2D] V10 | V11 | SIL: 0.6437 | DB: 1.7897 | CH: 970.82 | CENT: 2.4390 | OVER: 0.9798
[2D] V10 | V4 | SIL: 0.4531 | DB: 3.1993 | CH: 1034.61 | CENT: 0.9645 | OVER: 0.8896
[2D] V10 | V17 | SIL: 0.6810 | DB: 4.4919 | CH: 294.39 | CENT: 1.1277 | OVER: 0.9811
[2D] V10 | V3 | SIL: 0.6958 | DB: 1.8339 | CH: 1372.43 | CENT: 2.7125 | OVER: 0.9856
[2D] V10 | V16 | SIL: 0.6440 | DB: 2.2284 | CH: 952.31 | CENT: 2.0608 | OVER: 0.9677
[2D] V10 | V7 | SIL: 0.6992 | DB: 5.3765 | CH: 248.82 | CENT: 0.9553 | OVER: 0.9816
[2D] V10 | V9 | SIL: 0.4781 | DB: 3.1698 | CH: 910.57 | CENT: 0.9876 | OVER: 0.8964
[2D] V11 | V4 | SIL: 0.3378 | DB: 1.1886 | CH: 7011.73 | CENT: 1.6196 | OVER: 0.8248
[2D] V11 | V17 | SIL: 0.6070 | DB: 1.5999 | CH: 866.40 | CENT: 2.2493 | OVER: 0.9779
[2D] V11 | V3 | SIL: 0.3379 | DB: 1.2150 | CH: 6825.57 | CENT: 1.5932 | OVER: 0.8050
[2D] V11 | V16 | SIL: 0.3384 | DB: 1.1824 | CH: 6784.25 | CENT: 1.6244 | OVER: 0.8287
[2D] V11 | V7 | SIL: 0.6506 | DB: 15.0213 | CH: 21.47 | CENT: 0.3548 | OVER: 0.9815
[2D] V11 | V9 | SIL: 0.3363 | DB: 1.1971 | CH: 6894.62 | CENT: 1.6000 | OVER: 0.8191
[2D] V4 | V17 | SIL: 0.5431 | DB: 1.5471 | CH: 2235.15 | CENT: 2.0990 | OVER: 0.9442
[2D] V4 | V3 | SIL: 0.2921 | DB: 1.3302 | CH: 4787.94 | CENT: 1.4466 | OVER: 0.7128
[2D] V4 | V16 | SIL: 0.3300 | DB: 5.0907 | CH: 462.44 | CENT: 0.5595 | OVER: 0.7789
[2D] V4 | V7 | SIL: 0.6262 | DB: 3.8999 | CH: 293.27 | CENT: 1.1896 | OVER: 0.9668
[2D] V4 | V9 | SIL: 0.3460 | DB: 11.9463 | CH: 87.62 | CENT: 0.2487 | OVER: 0.8025
[2D] V17 | V3 | SIL: 0.6439 | DB: 1.1872 | CH: 1977.54 | CENT: 3.0003 | OVER: 0.9819
[2D] V17 | V16 | SIL: 0.5544 | DB: 2.0869 | CH: 1173.44 | CENT: 1.6614 | OVER: 0.9366
[2D] V17 | V7 | SIL: 0.6902 | DB: 7.9811 | CH: 90.59 | CENT: 0.6459 | OVER: 0.9824
[2D] V17 | V9 | SIL: 0.6067 | DB: 2.3935 | CH: 694.79 | CENT: 1.7197 | OVER: 0.9673
[2D] V3 | V16 | SIL: 0.5456 | DB: 1.6115 | CH: 1518.60 | CENT: 2.2261 | OVER: 0.9419
[2D] V3 | V7 | SIL: 0.6869 | DB: 2.6725 | CH: 776.89 | CENT: 1.9583 | OVER: 0.9868
[2D] V3 | V9 | SIL: 0.6456 | DB: 1.4210 | CH: 1339.81 | CENT: 3.1379 | OVER: 0.9780
[2D] V16 | V7 | SIL: 0.6376 | DB: 6.1656 | CH: 159.11 | CENT: 0.7899 | OVER: 0.9726
[2D] V16 | V9 | SIL: 0.3229 | DB: 2.7681 | CH: 1488.76 | CENT: 0.9542 | OVER: 0.7640
[2D] V7 | V9 | SIL: 0.6326 | DB: 5.3345 | CH: 209.97 | CENT: 0.8982 | OVER: 0.9756

CSV 2x2 salvo com sucesso!

Total 3x3: 120
[3D] V14 | V12 | V10 | SIL: 0.4554 | DB: 2.4356 | CH: 1629.82 | CENT: 1.5222 | OVER: 0.9374
[3D] V14 | V12 | V11 | SIL: 0.4428 | DB: 2.1350 | CH: 1879.52 | CENT: 1.7810 | OVER: 0.9369
[3D] V14 | V12 | V4 | SIL: 0.4110 | DB: 2.3852 | CH: 1794.32 | CENT: 1.5447 | OVER: 0.9104
[3D] V14 | V12 | V17 | SIL: 0.4760 | DB: 2.0944 | CH: 1970.41 | CENT: 1.7615 | OVER: 0.9418
[3D] V14 | V12 | V3 | SIL: 0.4336 | DB: 2.3701 | CH: 1703.07 | CENT: 1.5903 | OVER: 0.9285
[3D] V14 | V12 | V16 | SIL: 0.4206 | DB: 2.4921 | CH: 1506.00 | CENT: 1.5054 | OVER: 0.9176
[3D] V14 | V12 | V7 | SIL: 0.4984 | DB: 2.4952 | CH: 1390.85 | CENT: 1.5591 | OVER: 0.9565
[3D] V14 | V12 | V9 | SIL: 0.4602 | DB: 2.1518 | CH: 2069.52 | CENT: 1.7784 | OVER: 0.9340
[3D] V14 | V10 | V11 | SIL: 0.5584 | DB: 2.9308 | CH: 647.19 | CENT: 1.7772 | OVER: 0.9742
[3D] V14 | V10 | V4 | SIL: 0.5191 | DB: 2.9744 | CH: 908.04 | CENT: 1.5523 | OVER: 0.9513
[3D] V14 | V10 | V17 | SIL: 0.6010 | DB: 2.5979 | CH: 952.52 | CENT: 1.9493 | OVER: 0.9796
[3D] V14 | V10 | V3 | SIL: 0.5946 | DB: 2.2683 | CH: 1165.92 | CENT: 2.3022 | OVER: 0.9802
[3D] V14 | V10 | V16 | SIL: 0.5787 | DB: 2.7864 | CH: 762.74 | CENT: 1.9054 | OVER: 0.9741
[3D] V14 | V10 | V7 | SIL: 0.6410 | DB: 4.9215 | CH: 295.32 | CENT: 1.1877 | OVER: 0.9846
[3D] V14 | V10 | V9 | SIL: 0.5675 | DB: 2.8361 | CH: 803.52 | CENT: 1.8107 | OVER: 0.9648
[3D] V14 | V11 | V4 | SIL: 0.3813 | DB: 3.2531 | CH: 838.71 | CENT: 1.2619 | OVER: 0.8864
[3D] V14 | V11 | V17 | SIL: 0.5161 | DB: 2.0105 | CH: 1349.16 | CENT: 2.1537 | OVER: 0.9602
[3D] V14 | V11 | V3 | SIL: 0.4632 | DB: 2.6857 | CH: 862.23 | CENT: 1.6822 | OVER: 0.9436
[3D] V14 | V11 | V16 | SIL: 0.4035 | DB: 5.5252 | CH: 249.88 | CENT: 0.8029 | OVER: 0.9068
[3D] V14 | V11 | V7 | SIL: 0.5505 | DB: 5.5896 | CH: 195.78 | CENT: 0.9474 | OVER: 0.9736
[3D] V14 | V11 | V9 | SIL: 0.3833 | DB: 3.1265 | CH: 860.93 | CENT: 1.2876 | OVER: 0.9019
[3D] V14 | V4 | V17 | SIL: 0.5049 | DB: 2.2618 | CH: 1216.99 | CENT: 1.8951 | OVER: 0.9513
[3D] V14 | V4 | V3 | SIL: 0.4696 | DB: 2.5248 | CH: 1071.87 | CENT: 1.7499 | OVER: 0.9356
[3D] V14 | V4 | V16 | SIL: 0.3757 | DB: 4.8153 | CH: 436.42 | CENT: 0.8486 | OVER: 0.8750
[3D] V14 | V4 | V7 | SIL: 0.5625 | DB: 4.1965 | CH: 352.40 | CENT: 1.2548 | OVER: 0.9713
[3D] V14 | V4 | V9 | SIL: 0.2907 | DB: 10.4375 | CH: 114.38 | CENT: 0.3443 | OVER: 0.8433
[3D] V14 | V17 | V3 | SIL: 0.5880 | DB: 1.8625 | CH: 1443.67 | CENT: 2.5153 | OVER: 0.9777
[3D] V14 | V17 | V16 | SIL: 0.5294 | DB: 2.3200 | CH: 1087.74 | CENT: 1.8907 | OVER: 0.9587
[3D] V14 | V17 | V7 | SIL: 0.6161 | DB: 2.9585 | CH: 767.92 | CENT: 1.7535 | OVER: 0.9797
[3D] V14 | V17 | V9 | SIL: 0.4452 | DB: 2.4790 | CH: 1307.76 | CENT: 1.5435 | OVER: 0.9341
[3D] V14 | V3 | V16 | SIL: 0.5034 | DB: 2.3960 | CH: 1129.82 | CENT: 1.9331 | OVER: 0.9509
[3D] V14 | V3 | V7 | SIL: 0.5842 | DB: 2.6209 | CH: 942.62 | CENT: 1.9388 | OVER: 0.9790
[3D] V14 | V3 | V9 | SIL: 0.4069 | DB: 3.0230 | CH: 1014.37 | CENT: 1.3389 | OVER: 0.9098
[3D] V14 | V16 | V7 | SIL: 0.5530 | DB: 6.9912 | CH: 134.75 | CENT: 0.7480 | OVER: 0.9703
[3D] V14 | V16 | V9 | SIL: 0.3826 | DB: 4.1861 | CH: 555.42 | CENT: 0.9663 | OVER: 0.8888
[3D] V14 | V7 | V9 | SIL: 0.5549 | DB: 5.0936 | CH: 281.43 | CENT: 1.0303 | OVER: 0.9658
[3D] V12 | V10 | V11 | SIL: 0.4080 | DB: 1.9797 | CH: 2168.69 | CENT: 1.7900 | OVER: 0.9152
[3D] V12 | V10 | V4 | SIL: 0.3700 | DB: 2.3886 | CH: 1926.55 | CENT: 1.3791 | OVER: 0.9049
[3D] V12 | V10 | V17 | SIL: 0.4676 | DB: 2.0661 | CH: 1843.99 | CENT: 1.7363 | OVER: 0.9345
[3D] V12 | V10 | V3 | SIL: 0.4437 | DB: 2.0104 | CH: 1911.99 | CENT: 1.8341 | OVER: 0.9308
[3D] V12 | V10 | V16 | SIL: 0.3529 | DB: 2.3509 | CH: 1829.89 | CENT: 1.3850 | OVER: 0.8857
[3D] V12 | V10 | V7 | SIL: 0.4978 | DB: 2.5943 | CH: 988.01 | CENT: 1.4876 | OVER: 0.9483
[3D] V12 | V10 | V9 | SIL: 0.4513 | DB: 2.1394 | CH: 2056.03 | CENT: 1.7031 | OVER: 0.9359
[3D] V12 | V11 | V4 | SIL: 0.3522 | DB: 2.2777 | CH: 1937.59 | CENT: 1.5542 | OVER: 0.8740
[3D] V12 | V11 | V17 | SIL: 0.4331 | DB: 1.5200 | CH: 2890.81 | CENT: 2.1638 | OVER: 0.9354
[3D] V12 | V11 | V3 | SIL: 0.4238 | DB: 1.6868 | CH: 2222.20 | CENT: 2.1300 | OVER: 0.9185
[3D] V12 | V11 | V16 | SIL: 0.3538 | DB: 2.2362 | CH: 1876.74 | CENT: 1.5909 | OVER: 0.8672
[3D] V12 | V11 | V7 | SIL: 0.4571 | DB: 2.0243 | CH: 1681.79 | CENT: 1.8310 | OVER: 0.9458
[3D] V12 | V11 | V9 | SIL: 0.4009 | DB: 2.0226 | CH: 2222.12 | CENT: 1.8076 | OVER: 0.9004
[3D] V12 | V4 | V17 | SIL: 0.4168 | DB: 1.9125 | CH: 2284.29 | CENT: 1.8003 | OVER: 0.9136
[3D] V12 | V4 | V3 | SIL: 0.3553 | DB: 2.4775 | CH: 1681.11 | CENT: 1.4217 | OVER: 0.8705
[3D] V12 | V4 | V16 | SIL: 0.3202 | DB: 2.7569 | CH: 1474.49 | CENT: 1.2373 | OVER: 0.8592
[3D] V12 | V4 | V7 | SIL: 0.4391 | DB: 2.2598 | CH: 1665.03 | CENT: 1.6176 | OVER: 0.9272
[3D] V12 | V4 | V9 | SIL: 0.3400 | DB: 2.9956 | CH: 1333.91 | CENT: 1.1643 | OVER: 0.8844
[3D] V12 | V17 | V3 | SIL: 0.4564 | DB: 1.7044 | CH: 2344.32 | CENT: 2.0649 | OVER: 0.9413
[3D] V12 | V17 | V16 | SIL: 0.3982 | DB: 1.8831 | CH: 2593.44 | CENT: 1.7333 | OVER: 0.9054
[3D] V12 | V17 | V7 | SIL: 0.4998 | DB: 2.0186 | CH: 1723.91 | CENT: 1.8382 | OVER: 0.9558
[3D] V12 | V17 | V9 | SIL: 0.4388 | DB: 1.8024 | CH: 2555.09 | CENT: 1.9083 | OVER: 0.9242
[3D] V12 | V3 | V16 | SIL: 0.3806 | DB: 2.2151 | CH: 1798.25 | CENT: 1.6135 | OVER: 0.8846
[3D] V12 | V3 | V7 | SIL: 0.5221 | DB: 2.3926 | CH: 1163.75 | CENT: 1.8388 | OVER: 0.9619
[3D] V12 | V3 | V9 | SIL: 0.4326 | DB: 1.9277 | CH: 2214.33 | CENT: 1.9081 | OVER: 0.9186
[3D] V12 | V16 | V7 | SIL: 0.4503 | DB: 2.3593 | CH: 1314.65 | CENT: 1.5721 | OVER: 0.9346
[3D] V12 | V16 | V9 | SIL: 0.3460 | DB: 2.6449 | CH: 1587.49 | CENT: 1.3353 | OVER: 0.8718
[3D] V12 | V7 | V9 | SIL: 0.4663 | DB: 2.0440 | CH: 2026.29 | CENT: 1.7683 | OVER: 0.9389
[3D] V10 | V11 | V4 | SIL: 0.3329 | DB: 4.1541 | CH: 598.98 | CENT: 0.8989 | OVER: 0.8854
[3D] V10 | V11 | V17 | SIL: 0.6054 | DB: 3.5672 | CH: 383.78 | CENT: 1.6149 | OVER: 0.9846
[3D] V10 | V11 | V3 | SIL: 0.6333 | DB: 1.8186 | CH: 1123.15 | CENT: 3.1524 | OVER: 0.9896
[3D] V10 | V11 | V16 | SIL: 0.5802 | DB: 2.4049 | CH: 649.30 | CENT: 2.2420 | OVER: 0.9798
[3D] V10 | V11 | V7 | SIL: 0.6284 | DB: 6.5333 | CH: 145.79 | CENT: 0.9414 | OVER: 0.9842
[3D] V10 | V11 | V9 | SIL: 0.5835 | DB: 2.4126 | CH: 719.21 | CENT: 2.2244 | OVER: 0.9779
[3D] V10 | V4 | V17 | SIL: 0.5352 | DB: 2.8970 | CH: 885.98 | CENT: 1.5943 | OVER: 0.9615
[3D] V10 | V4 | V3 | SIL: 0.5132 | DB: 2.7108 | CH: 921.22 | CENT: 1.7154 | OVER: 0.9510
[3D] V10 | V4 | V16 | SIL: 0.2985 | DB: 3.5222 | CH: 928.90 | CENT: 0.9043 | OVER: 0.8781
[3D] V10 | V4 | V7 | SIL: 0.5302 | DB: 3.7135 | CH: 617.83 | CENT: 1.2385 | OVER: 0.9567
[3D] V10 | V4 | V9 | SIL: 0.4176 | DB: 3.5037 | CH: 859.20 | CENT: 1.1063 | OVER: 0.9200
[3D] V10 | V17 | V3 | SIL: 0.6376 | DB: 2.6647 | CH: 747.40 | CENT: 2.1687 | OVER: 0.9864
[3D] V10 | V17 | V16 | SIL: 0.6000 | DB: 3.5578 | CH: 444.66 | CENT: 1.5420 | OVER: 0.9778
[3D] V10 | V17 | V7 | SIL: 0.6345 | DB: 6.8102 | CH: 148.44 | CENT: 0.8461 | OVER: 0.9840
[3D] V10 | V17 | V9 | SIL: 0.6066 | DB: 3.3724 | CH: 524.17 | CENT: 1.6489 | OVER: 0.9803
[3D] V10 | V3 | V16 | SIL: 0.5931 | DB: 2.1897 | CH: 888.41 | CENT: 2.4308 | OVER: 0.9823
[3D] V10 | V3 | V7 | SIL: 0.6526 | DB: 3.0057 | CH: 715.07 | CENT: 2.0233 | OVER: 0.9877
[3D] V10 | V3 | V9 | SIL: 0.6458 | DB: 2.0347 | CH: 1018.49 | CENT: 2.8952 | OVER: 0.9899
[3D] V10 | V16 | V7 | SIL: 0.6240 | DB: 5.5707 | CH: 205.22 | CENT: 1.0604 | OVER: 0.9820
[3D] V10 | V16 | V9 | SIL: 0.3742 | DB: 2.5419 | CH: 1485.30 | CENT: 1.3603 | OVER: 0.8897
[3D] V10 | V7 | V9 | SIL: 0.6453 | DB: 4.1598 | CH: 372.15 | CENT: 1.4349 | OVER: 0.9856
[3D] V11 | V4 | V17 | SIL: 0.4791 | DB: 1.9880 | CH: 1179.37 | CENT: 2.1381 | OVER: 0.9580
[3D] V11 | V4 | V3 | SIL: 0.2321 | DB: 1.6705 | CH: 3779.60 | CENT: 1.5952 | OVER: 0.8008
[3D] V11 | V4 | V16 | SIL: 0.2315 | DB: 1.6503 | CH: 3760.18 | CENT: 1.5914 | OVER: 0.8226
[3D] V11 | V4 | V7 | SIL: 0.5326 | DB: 3.5820 | CH: 373.72 | CENT: 1.4391 | OVER: 0.9723
[3D] V11 | V4 | V9 | SIL: 0.2404 | DB: 1.6056 | CH: 3996.38 | CENT: 1.6195 | OVER: 0.8256
[3D] V11 | V17 | V3 | SIL: 0.5651 | DB: 1.4343 | CH: 1285.95 | CENT: 3.0472 | OVER: 0.9870
[3D] V11 | V17 | V16 | SIL: 0.4750 | DB: 2.0193 | CH: 930.51 | CENT: 2.0504 | OVER: 0.9605
[3D] V11 | V17 | V7 | SIL: 0.5986 | DB: 4.7898 | CH: 230.93 | CENT: 1.1867 | OVER: 0.9849
[3D] V11 | V17 | V9 | SIL: 0.5347 | DB: 2.4330 | CH: 619.57 | CENT: 2.0049 | OVER: 0.9744
[3D] V11 | V3 | V16 | SIL: 0.5500 | DB: 1.7100 | CH: 722.28 | CENT: 2.9097 | OVER: 0.9802
[3D] V11 | V3 | V7 | SIL: 0.6030 | DB: 3.0430 | CH: 464.48 | CENT: 1.9100 | OVER: 0.9894
[3D] V11 | V3 | V9 | SIL: 0.5909 | DB: 1.6732 | CH: 815.16 | CENT: 3.2463 | OVER: 0.9877
[3D] V11 | V16 | V7 | SIL: 0.5747 | DB: 10.0078 | CH: 46.86 | CENT: 0.5836 | OVER: 0.9794
[3D] V11 | V16 | V9 | SIL: 0.2426 | DB: 4.0699 | CH: 721.81 | CENT: 0.8547 | OVER: 0.7756
[3D] V11 | V7 | V9 | SIL: 0.5742 | DB: 6.9179 | CH: 104.66 | CENT: 0.8425 | OVER: 0.9797
[3D] V4 | V17 | V3 | SIL: 0.5445 | DB: 1.9763 | CH: 1122.86 | CENT: 2.3747 | OVER: 0.9697
[3D] V4 | V17 | V16 | SIL: 0.4424 | DB: 2.8240 | CH: 929.03 | CENT: 1.4647 | OVER: 0.9247
[3D] V4 | V17 | V7 | SIL: 0.5918 | DB: 3.7626 | CH: 395.23 | CENT: 1.4401 | OVER: 0.9796
[3D] V4 | V17 | V9 | SIL: 0.3855 | DB: 4.7741 | CH: 423.04 | CENT: 0.8364 | OVER: 0.8879
[3D] V4 | V3 | V16 | SIL: 0.3563 | DB: 4.8063 | CH: 445.90 | CENT: 0.8321 | OVER: 0.8503
[3D] V4 | V3 | V7 | SIL: 0.5907 | DB: 2.8340 | CH: 589.73 | CENT: 1.9505 | OVER: 0.9843
[3D] V4 | V3 | V9 | SIL: 0.3088 | DB: 12.2328 | CH: 79.21 | CENT: 0.3187 | OVER: 0.8372
[3D] V4 | V16 | V7 | SIL: 0.5404 | DB: 7.2627 | CH: 108.21 | CENT: 0.7331 | OVER: 0.9678
[3D] V4 | V16 | V9 | SIL: 0.1926 | DB: 5.3408 | CH: 400.04 | CENT: 0.5735 | OVER: 0.8261
[3D] V4 | V7 | V9 | SIL: 0.5172 | DB: 6.3760 | CH: 171.89 | CENT: 0.7879 | OVER: 0.9541
[3D] V17 | V3 | V16 | SIL: 0.5512 | DB: 2.1148 | CH: 999.31 | CENT: 2.2436 | OVER: 0.9709
[3D] V17 | V3 | V7 | SIL: 0.6138 | DB: 2.5018 | CH: 840.38 | CENT: 2.1005 | OVER: 0.9864
[3D] V17 | V3 | V9 | SIL: 0.5988 | DB: 1.9781 | CH: 1025.37 | CENT: 2.6516 | OVER: 0.9835
[3D] V17 | V16 | V7 | SIL: 0.5889 | DB: 5.1966 | CH: 214.49 | CENT: 1.0347 | OVER: 0.9782
[3D] V17 | V16 | V9 | SIL: 0.4626 | DB: 2.3864 | CH: 969.90 | CENT: 1.7104 | OVER: 0.9427
[3D] V17 | V7 | V9 | SIL: 0.6054 | DB: 5.3173 | CH: 211.16 | CENT: 1.0730 | OVER: 0.9813
[3D] V3 | V16 | V7 | SIL: 0.6112 | DB: 3.1687 | CH: 504.80 | CENT: 1.8526 | OVER: 0.9839
[3D] V3 | V16 | V9 | SIL: 0.5594 | DB: 2.0510 | CH: 971.48 | CENT: 2.5653 | OVER: 0.9703
[3D] V3 | V7 | V9 | SIL: 0.6059 | DB: 3.2189 | CH: 496.33 | CENT: 1.8092 | OVER: 0.9868
[3D] V16 | V7 | V9 | SIL: 0.5865 | DB: 7.1362 | CH: 95.15 | CENT: 0.8182 | OVER: 0.9745

CSV 3x3 salvo com sucesso!

,Features,Silhouette,Davies_Bouldin,Calinski_Harabasz,Dist_Centroides,Overlap_GMM
0,V14 | V12,0.546199,1.747836,2741.178112,1.787456,0.941045
1,V14 | V10,0.639580,2.492396,994.400390,1.753721,0.971431
2,V14 | V11,0.401122,4.999709,367.216583,0.677617,0.852484
3,V14 | V4,0.428688,3.199823,973.994260,1.018098,0.848775
4,V14 | V17,0.611298,1.716242,1708.672676,2.021481,0.959384

,Features,Silhouette,Davies_Bouldin,Calinski_Harabasz,Dist_Centroides,Overlap_GMM
0,V14 | V12 | V10,0.455383,2.435582,1629.820319,1.522208,0.937417
1,V14 | V12 | V11,0.442753,2.135009,1879.522273,1.781022,0.936897
2,V14 | V12 | V4,0.410957,2.385204,1794.318489,1.544737,0.910421
3,V14 | V12 | V17,0.475969,2.094408,1970.406839,1.761508,0.941782
4,V14 | V12 | V3,0.433564,2.370133,1703.069380,1.590306,0.928537

✓ Processo concluído em: 22m 21.02s