### PACOTES

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time
import itertools

from sklearn.preprocessing import MinMaxScaler

import plotly.express as px 
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    roc_auc_score,
    average_precision_score
)
from sklearn.model_selection import StratifiedKFold
from scipy.stats import ks_2samp
from sklearn.preprocessing import RobustScaler
from sklearn.mixture import GaussianMixture

from sklearn.metrics import (

    silhouette_score,
    davies_bouldin_score

)
from scipy.stats import wasserstein_distance
from scipy.spatial.distance import mahalanobis
import time

In [2]:

inicio = time.time()
df_resumo = pd.read_csv('resumo_features.csv')
df = pd.read_csv('creditcard.csv')

# AJUSTE DE TIPOS
df_resumo['Comparacao_dis_whith'] = pd.to_numeric(
    df_resumo['Comparacao_dis_whith'],
    errors='coerce'
)

# MANN-WHITNEY SCORE
# Quanto menor o p-value -> melhor
df_resumo['MannWhitney_Score'] = -np.log10(
    df_resumo['Comparacao_dis_whith'] + 1e-300
)

# CORRELAÇÃO ABSOLUTA
df_resumo['Corr_spearman_abs'] = abs(
    df_resumo['Correlacao_spearman']
)

# AJUSTE DE MÉTRICAS DISTRIBUCIONAIS

# KL e Wasser podem explodir
# Aplicamos log para estabilizar

df_resumo['divergencia_kl'] = np.log1p(
    abs(df_resumo['divergencia_kl'])
)

df_resumo['Wasser'] = np.log1p(
    abs(df_resumo['Wasser'])
)

# AJUSTE DE NORMALIDADE

# Quanto MENOR distância da normalidade -> melhor
df_resumo['Normalidade_Score'] = 1 / (
    1 + abs(df_resumo['Normalidade'])
)

# AJUSTE DE ASSIMETRIA
df_resumo['Skewness_Score'] = 1 / (
    1 + abs(df_resumo['Assimetria'])
)


# AJUSTE DE CURTOSE
df_resumo['Kurtosis_Score'] = 1 / (
    1 + abs(df_resumo['Curtose'])
)

# AJUSTE DE OUTLIERS
df_resumo['Outlier_Score'] = 1 / (
    1 + df_resumo['Qnd_Outliers']
)

# MÉTRICAS UTILIZADAS
metricas = [

    # INDISPENSÁVEL
    'Curva ROC',
    'KS',

    # MUITO IMPORTANTE
    'divergencia_kl',
    'Wasser',

    # IMPORTANTE
    'inf_mutua',
    'MannWhitney_Score',

    # BOM
    'Normalidade_Score',
    'Sep_mediana_norm',

    # ÚTIL
    'Skewness_Score',
    'Kurtosis_Score',

    # ACESSÓRIO
    'Corr_spearman_abs',
    'Outlier_Score'
]


# TRATAMENTO DE NaN
df_resumo[metricas] = df_resumo[
    metricas
].fillna(0)


# NORMALIZAÇÃO ROBUSTA
# Melhor para fraude/outliers

scaler = RobustScaler()

df_norm = df_resumo.copy()

df_norm[metricas] = scaler.fit_transform(
    df_norm[metricas]
)


# MIN-MAX FINAL
# Após robust scaling

for col in metricas:

    minimo = df_norm[col].min()
    maximo = df_norm[col].max()

    df_norm[col] = (
        (df_norm[col] - minimo)
        /
        (maximo - minimo + 1e-9)
    )

# =========================================================
# SCORE FINAL
# =========================================================

df_norm['Score_Final'] = (

    # INDISPENSÁVEL -> 0.25
    df_norm['Curva ROC'] * 0.125 +
    df_norm['KS'] * 0.125 +

    # MUITO IMPORTANTE -> 0.21
    df_norm['divergencia_kl'] * 0.105 +
    df_norm['Wasser'] * 0.105 +

    # IMPORTANTE -> 0.17
    df_norm['inf_mutua'] * 0.085 +
    df_norm['MannWhitney_Score'] * 0.085 +

    # BOM -> 0.13
    df_norm['Normalidade_Score'] * 0.065 +
    df_norm['Sep_mediana_norm'] * 0.065 +

    # ÚTIL -> 0.09
    df_norm['Skewness_Score'] * 0.045 +
    df_norm['Kurtosis_Score'] * 0.045 +

    # ACESSÓRIO -> 0.05
    df_norm['Corr_spearman_abs'] * 0.025 +
    df_norm['Outlier_Score'] * 0.025
)


# GARANTIR SEM NaN
df_norm['Score_Final'] = df_norm[
    'Score_Final'
].fillna(0)

# RANKING FINAL
ranking = df_norm.sort_values(
    'Score_Final',
    ascending=False
).reset_index(drop=True)

# POSIÇÃO
ranking.insert(
    0,
    'Posicao_Rank',
    ranking.index + 1
)

# EXIBIÇÃO
pd.set_option(
    'display.max_columns',
    None
)

display(ranking)

# SALVAR CSV
ranking.to_csv(
    'individual_score_feature_individuais.csv',
    index=False
)

print('\nCSV salvo com sucesso!')

,Posicao_Rank,Feature,Normalidade,Qnd_Outliers,Sep_mediana_norm,Comparacao_dis_whith,Correlacao_spearman,inf_mutua,divergencia_kl,Curva ROC,KS,Wasser,Assimetria,Curtose,MannWhitney_Score,Corr_spearman_abs,Normalidade_Score,Skewness_Score,Kurtosis_Score,Outlier_Score,Score_Final
0,1,V14,0,14149,1.000000,1.471581e-260,-0.064613,0.984641,1.000000,1.000000,1.000000,0.211410,1.995165,23.879022,1.000000,1.000000,0.0,0.305756,0.046824,0.000045,0.651760
1,2,V12,0,15348,0.796989,8.416027e-247,-0.062870,0.917286,0.840947,0.972118,0.924927,0.201544,2.278389,20.241493,0.946936,0.972125,0.0,0.274060,0.055062,0.000040,0.595970
2,3,V10,0,9496,0.579452,9.611131e-222,-0.059564,0.908347,0.894367,0.919245,0.950893,0.192730,1.187134,31.987656,0.850284,0.919255,0.0,0.441298,0.035000,0.000080,0.579477
3,4,V11,0,780,0.497847,4.910592e-226,0.060143,0.820345,0.725013,0.928507,0.889460,0.157954,0.356504,1.633872,0.866838,0.928514,0.0,0.748947,0.453109,0.001255,0.573065
4,5,V4,0,11148,0.415041,3.625904e-248,0.063045,0.586806,0.805397,0.974920,0.902628,0.173101,0.676289,2.635388,0.952203,0.974924,0.0,0.594410,0.327929,0.000064,0.561109
5,6,V17,0,7420,0.870823,9.219384e-124,-0.044335,1.000000,0.905760,0.675706,0.875582,0.212480,3.844894,94.798034,0.472352,0.675708,0.0,0.165685,0.011212,0.000109,0.517935
6,7,V3,0,3363,0.486416,1.211048e-219,-0.059278,0.583784,0.718940,0.914680,0.822726,0.212220,2.240144,26.619062,0.842183,0.914681,0.0,0.278017,0.042052,0.000272,0.505049
7,8,V16,0,8184,0.580474,1.808172e-156,-0.049936,0.733854,0.745415,0.765280,0.800845,0.165757,1.100960,10.418927,0.598510,0.765281,0.0,0.461906,0.103528,0.000097,0.486999
8,9,V7,0,8948,0.346706,1.464234e-146,-0.048308,0.457887,0.709440,0.739240,0.767815,0.191285,2.553894,405.600275,0.560292,0.739245,0.0,0.248076,0.001663,0.000086,0.421761
9,10,V9,0,8283,0.272512,8.943723e-154,-0.049499,0.498804,0.482208,0.758284,0.660477,0.127076,0.554677,3.731224,0.588117,0.758292,0.0,0.645688,0.251678,0.000095,0.410763
10,11,V2,0,13526,0.221554,1.650438e-163,0.051062,0.366738,0.652029,0.783279,0.732939,0.154597,4.624841,95.771404,0.625663,0.783288,0.0,0.134235,0.011086,0.000048,0.399101
11,12,V18,0,7533,0.274983,2.648962e-77,-0.034872,0.503840,0.449384,0.524375,0.567532,0.118919,0.259879,2.578275,0.293154,0.524372,0.0,0.811075,0.333184,0.000107,0.346382
12,13,V21,0,14497,0.113302,8.673355e-80,0.035442,0.269042,0.658528,0.533488,0.586854,0.087094,3.592972,207.283380,0.302739,0.533488,0.0,0.178125,0.004465,0.000043,0.295854
13,14,V1,0,7062,0.164473,1.740785e-113,-0.042424,0.228125,0.262744,0.645134,0.531826,0.177403,3.280650,32.486088,0.432715,0.645146,0.0,0.195581,0.034460,0.000116,0.286681
14,15,V6,0,22965,0.115800,2.231002e-93,-0.038410,0.260985,0.436498,0.580947,0.545958,0.086852,1.826571,42.641724,0.355156,0.580953,0.0,0.327639,0.026143,0.000018,0.286158
15,16,V27,0,39163,0.131614,1.414589e-51,0.028311,0.268035,0.764981,0.419450,0.524451,0.051909,1.170203,244.984919,0.193919,0.419447,0.0,0.445218,0.003585,0.000000,0.282264
16,17,tempo_desde_a_primeira_transacao,0,0,0.020153,4.386159e-10,-0.011692,0.203450,0.008226,0.153673,0.142081,1.000000,0.035567,1.293528,0.033879,0.153670,0.0,1.000000,0.520538,1.000000,0.261582
17,18,V5,0,12295,0.144326,3.053712e-58,-0.030147,0.261362,0.496302,0.448817,0.482284,0.146007,2.425889,206.900907,0.219630,0.448809,0.0,0.259629,0.004476,0.000056,0.257202
18,19,V19,0,10205,0.105324,2.401960e-33,0.022546,0.145663,0.276783,0.327259,0.352651,0.056357,0.109191,1.724918,0.123603,0.327251,0.0,0.929567,0.437927,0.000072,0.219422
19,20,V28,0,30342,0.051035,1.203683e-27,0.020417,0.195896,0.628205,0.293207,0.395677,0.020084,11.192032,933.381095,0.101617,0.293203,0.0,0.029006,0.000000,0.000007,0.191422
20,21,V8,0,24134,0.064204,8.509891e-34,0.022706,0.199295,0.389259,0.329815,0.395598,0.132442,8.521899,220.583080,0.125341,0.329810,0.0,0.054280,0.004120,0.000016,0.188096
21,22,V20,0,27770,0.056890,1.128104e-30,0.021574,0.112300,0.434619,0.311710,0.389932,0.041662,2.037145,271.011334,0.113297,0.311706,0.0,0.300685,0.003119,0.000010,0.182052
22,23,valor_de_transacao,0,31904,0.000000,8.578472e-06,-0.008339,0.153217,0.407845,0.100041,0.271770,0.399682,16.977635,845.077788,0.017327,0.100048,0.0,0.000000,0.000134,0.000006,0.148270
23,24,V24,0,4774,0.016692,9.423066e-07,-0.009188,0.041168,0.281482,0.113628,0.090875,0.006312,0.552496,0.618839,0.021027,0.113625,0.0,0.646681,0.738018,0.000184,0.127309
24,25,V13,0,3368,0.000184,5.121481e-02,-0.003653,0.011708,0.049715,0.025119,0.057659,0.006128,0.065233,0.195275,0.002762,0.025108,0.0,0.970448,1.000000,0.000271,0.106757
25,26,V26,0,5596,0.009438,3.531905e-03,0.005466,0.023291,0.269617,0.054113,0.041926,0.000000,0.576690,0.918969,0.007242,0.054102,0.0,0.635820,0.622390,0.000153,0.101499
26,27,V15,0,2894,0.009156,1.295082e-01,-0.002841,0.000000,0.107053,0.012126,0.007078,0.004082,0.308421,0.284743,0.001208,0.012122,0.0,0.778717,0.930272,0.000320,0.091983
27,28,V25,0,5367,0.012395,1.246293e-02,0.004682,0.023291,0.210128,0.041573,0.038563,0.011027,0.415790,4.290316,0.005130,0.041564,0.0,0.715026,0.224945,0.000161,0.079801
28,29,V23,0,18541,0.006876,7.419609e-03,-0.005017,0.056276,0.309442,0.046926,0.158070,0.031466,5.875109,440.080912,0.005998,0.046921,0.0,0.098708,0.001432,0.000028,0.072840
29,30,V22,0,1317,0.000923,2.663947e-01,0.002083,0.004784,0.000000,0.000000,0.000000,0.018208,0.213256,2.832896,0.000000,0.000000,0.0,0.844592,0.310965,0.000733,0.054397

CSV salvo com sucesso!

### TOP 10

In [3]:

# CARREGAR CSV DO RANKING
ranking = pd.read_csv('individual_score_feature_individuais.csv')

ranking = ranking.sort_values(
    by='Score_Final',
    ascending=False
)

top10 = ranking.head(10)

# ATRIBUINDO ÀS VARIÁVEIS
Primeiro_lugar = top10.iloc[0]['Feature']
Segundo_lugar = top10.iloc[1]['Feature']
Terceiro_lugar = top10.iloc[2]['Feature']
Quarto_lugar = top10.iloc[3]['Feature']
Quinto_lugar = top10.iloc[4]['Feature']
Sexto_lugar = top10.iloc[5]['Feature']
Setimo_lugar = top10.iloc[6]['Feature']
Oitavo_lugar = top10.iloc[7]['Feature']
Nono_lugar = top10.iloc[8]['Feature']
Decimo_lugar = top10.iloc[9]['Feature']

# PRINT TOP 10
print('TOP 10 FEATURES:\n')

for i, row in top10.iterrows():

    print(
        f"{row['Posicao_Rank']}º -> "
        f"{row['Feature']}"
    )

# LISTA FINAL
features_top10 = top10['Feature'].tolist()
print('\nLista Top 10:\n')
print(features_top10)

TOP 10 FEATURES:

1º -> V14
2º -> V12
3º -> V10
4º -> V11
5º -> V4
6º -> V17
7º -> V3
8º -> V16
9º -> V7
10º -> V9

Lista Top 10:

['V14', 'V12', 'V10', 'V11', 'V4', 'V17', 'V3', 'V16', 'V7', 'V9']

 ### COMBINACOES 2X2

In [4]:

y = df['status_fraude']

sample_size_silhouette = 14240

# PEGANDO TOP 10 FEATURES
features_top10 = top10['Feature'].tolist()


# COMBINAÇÕES 2x2
combinacoes_2x2 = list(
    itertools.combinations(
        features_top10,
        2
    )
)

print(
    f'Total de combinações: '
    f'{len(combinacoes_2x2)}\n'
)

# DICIONÁRIO
dic_combinacoes = {}

# LOOP PRINCIPAL

for i, (f1, f2) in enumerate(
    combinacoes_2x2,
    start=1
):

    try:

        # MATRIZ COMPLETA

        X = df[[f1, f2]].values

        # PADRONIZAÇÃO
        scaler = StandardScaler()

        X_scaled = scaler.fit_transform(X)

        # GMM

        gmm = GaussianMixture(

            n_components=2,
            covariance_type='diag',
            random_state=42,
            max_iter=100

        )

        gmm.fit(X_scaled)

        # LABELS

        labels = gmm.predict(X_scaled)

        # 1) SILHOUETTE
        # Apenas em 5% da base

        sample_size = min(
            sample_size_silhouette,
            len(X_scaled)
        )

        idx = np.random.choice(

            len(X_scaled),
            size=sample_size,
            replace=False

        )

        silhouette = silhouette_score(

            X_scaled[idx],
            labels[idx]

        )

        # 2) DAVIES-BOULDIN

        davies = davies_bouldin_score(
            X_scaled,
            labels
        )

        # 3) WASSERSTEIN

        classe_0 = X_scaled[y == 0]
        classe_1 = X_scaled[y == 1]

        wasser_1 = wasserstein_distance(

            classe_0[:, 0],
            classe_1[:, 0]

        )

        wasser_2 = wasserstein_distance(

            classe_0[:, 1],
            classe_1[:, 1]

        )

        wasser_final = (
            wasser_1 + wasser_2
        ) / 2

        # 4) MAHALANOBIS
        media_0 = np.mean(
            classe_0,
            axis=0
        )

        media_1 = np.mean(
            classe_1,
            axis=0
        )

        cov = np.cov(
            X_scaled.T
        )

        inv_cov = np.linalg.pinv(
            cov
        )

        maha = mahalanobis(

            media_0,
            media_1,
            inv_cov

        )

        # 5) OVERLAP GAUSSIANO
        probs = gmm.predict_proba(
            X_scaled
        )

        overlap = np.mean(
            np.min(probs, axis=1)
        )

        overlap_score = 1 - overlap

        # SALVANDO
        chave = f'Combo_{i}'

        dic_combinacoes[chave] = {

            'Feature_1': f1,
            'Feature_2': f2,

            'Silhouette': round(
                float(silhouette), 6
            ),

            'Davies_Bouldin': round(
                float(davies), 6
            ),

            'Wasserstein': round(
                float(wasser_final), 6
            ),

            'Mahalanobis': round(
                float(maha), 6
            ),

            'Overlap_Gaussiano': round(
                float(overlap_score), 6
            )
        }


        # PRINT

        print(

            f'{chave} -> '

            f'{f1} / {f2} '

            f'| SIL: {silhouette:.4f} '

            f'| DB: {davies:.4f} '

            f'| WASSER: {wasser_final:.4f} '

            f'| MAHA: {maha:.4f} '

            f'| OVERLAP: {overlap_score:.4f}'
        )

    except Exception as e:

        print(
            f'Erro em {f1} / {f2}: {e}'
        )

# DATAFRAME FINAL

df_combinacoes = pd.DataFrame.from_dict(
    dic_combinacoes,
    orient='index'
).reset_index()

df_combinacoes.rename(
    columns={'index': 'Combo'},
    inplace=True
)

display(df_combinacoes)

# SALVAR CSV
df_combinacoes.to_csv(
    '2x2_visu_metfeat.csv',
    index=False
)

print('\nCSV salvo com sucesso!')

Total de combinações: 45

Combo_1 -> V14 / V12 | SIL: 0.5449 | DB: 1.7119 | WASSER: 6.7805 | MAHA: 9.6154 | OVERLAP: 0.9403
Combo_2 -> V14 / V10 | SIL: 0.6344 | DB: 2.5124 | WASSER: 6.2542 | MAHA: 8.9640 | OVERLAP: 0.9718
Combo_3 -> V14 / V11 | SIL: 0.4052 | DB: 4.4043 | WASSER: 5.5076 | MAHA: 8.1845 | OVERLAP: 0.8536
Combo_4 -> V14 / V4 | SIL: 0.4235 | DB: 3.1432 | WASSER: 5.2496 | MAHA: 7.9627 | OVERLAP: 0.8497
Combo_5 -> V14 / V17 | SIL: 0.6102 | DB: 1.6574 | WASSER: 7.8023 | MAHA: 10.7185 | OVERLAP: 0.9585
Combo_6 -> V14 / V3 | SIL: 0.5269 | DB: 2.0791 | WASSER: 5.9662 | MAHA: 8.6411 | OVERLAP: 0.9214
Combo_7 -> V14 / V16 | SIL: 0.4595 | DB: 4.8672 | WASSER: 6.0259 | MAHA: 8.6877 | OVERLAP: 0.8718
Combo_8 -> V14 / V7 | SIL: 0.6535 | DB: 4.7946 | WASSER: 5.9044 | MAHA: 8.5680 | OVERLAP: 0.9714
Combo_9 -> V14 / V9 | SIL: 0.4266 | DB: 2.8120 | WASSER: 4.8196 | MAHA: 7.6561 | OVERLAP: 0.8593
Combo_10 -> V12 / V10 | SIL: 0.4696 | DB: 1.5714 | WASSER: 5.7490 | MAHA: 8.1642 | OVERLAP: 0.8959
Combo_11 -> V12 / V11 | SIL: 0.4628 | DB: 1.2749 | WASSER: 5.0024 | MAHA: 7.2998 | OVERLAP: 0.8758
Combo_12 -> V12 / V4 | SIL: 0.4169 | DB: 1.9538 | WASSER: 4.7444 | MAHA: 7.0502 | OVERLAP: 0.8516
Combo_13 -> V12 / V17 | SIL: 0.5137 | DB: 1.2113 | WASSER: 7.2970 | MAHA: 10.0592 | OVERLAP: 0.9206
Combo_14 -> V12 / V3 | SIL: 0.4897 | DB: 1.3414 | WASSER: 5.4610 | MAHA: 7.8083 | OVERLAP: 0.9005
Combo_15 -> V12 / V16 | SIL: 0.4355 | DB: 1.7418 | WASSER: 5.5207 | MAHA: 7.8599 | OVERLAP: 0.8562
Combo_16 -> V12 / V7 | SIL: 0.5535 | DB: 1.6772 | WASSER: 5.3992 | MAHA: 7.7274 | OVERLAP: 0.9394
Combo_17 -> V12 / V9 | SIL: 0.4630 | DB: 1.7607 | WASSER: 4.3144 | MAHA: 6.7020 | OVERLAP: 0.8779
Combo_18 -> V10 / V11 | SIL: 0.6611 | DB: 1.8047 | WASSER: 4.4761 | MAHA: 6.4176 | OVERLAP: 0.9807
Combo_19 -> V10 / V4 | SIL: 0.4542 | DB: 3.1914 | WASSER: 4.2181 | MAHA: 6.1321 | OVERLAP: 0.8911
Combo_20 -> V10 / V17 | SIL: 0.6651 | DB: 3.9846 | WASSER: 6.7708 | MAHA: 9.4385 | OVERLAP: 0.9808
Combo_21 -> V10 / V3 | SIL: 0.6836 | DB: 1.7102 | WASSER: 4.9347 | MAHA: 6.9905 | OVERLAP: 0.9853
Combo_22 -> V10 / V16 | SIL: 0.6504 | DB: 2.1283 | WASSER: 4.9944 | MAHA: 7.0481 | OVERLAP: 0.9682
Combo_23 -> V10 / V7 | SIL: 0.6988 | DB: 4.7237 | WASSER: 4.8729 | MAHA: 6.9000 | OVERLAP: 0.9815
Combo_24 -> V10 / V9 | SIL: 0.4795 | DB: 3.0371 | WASSER: 3.7881 | MAHA: 5.7284 | OVERLAP: 0.8956
Combo_25 -> V11 / V4 | SIL: 0.3395 | DB: 1.1914 | WASSER: 3.4716 | MAHA: 4.9230 | OVERLAP: 0.8235
Combo_26 -> V11 / V17 | SIL: 0.6113 | DB: 1.7202 | WASSER: 6.0242 | MAHA: 8.7016 | OVERLAP: 0.9777
Combo_27 -> V11 / V3 | SIL: 0.3314 | DB: 1.2093 | WASSER: 4.1881 | MAHA: 5.9582 | OVERLAP: 0.8053
Combo_28 -> V11 / V16 | SIL: 0.3421 | DB: 1.1708 | WASSER: 4.2478 | MAHA: 6.0256 | OVERLAP: 0.8289
Combo_29 -> V11 / V7 | SIL: 0.6383 | DB: 10.6638 | WASSER: 4.1263 | MAHA: 5.8517 | OVERLAP: 0.9813
Combo_30 -> V11 / V9 | SIL: 0.3368 | DB: 1.2038 | WASSER: 3.0415 | MAHA: 4.4100 | OVERLAP: 0.8207
Combo_31 -> V4 / V17 | SIL: 0.5409 | DB: 1.5645 | WASSER: 5.7662 | MAHA: 8.4933 | OVERLAP: 0.9445
Combo_32 -> V4 / V3 | SIL: 0.2908 | DB: 1.3264 | WASSER: 3.9302 | MAHA: 5.6496 | OVERLAP: 0.7116
Combo_33 -> V4 / V16 | SIL: 0.3289 | DB: 5.1058 | WASSER: 3.9898 | MAHA: 5.7206 | OVERLAP: 0.7788
Combo_34 -> V4 / V7 | SIL: 0.6235 | DB: 3.2638 | WASSER: 3.8684 | MAHA: 5.5371 | OVERLAP: 0.9669
Combo_35 -> V4 / V9 | SIL: 0.3499 | DB: 12.4604 | WASSER: 2.7835 | MAHA: 3.9831 | OVERLAP: 0.8029
Combo_36 -> V17 / V3 | SIL: 0.6391 | DB: 1.2807 | WASSER: 6.4828 | MAHA: 9.1324 | OVERLAP: 0.9822
Combo_37 -> V17 / V16 | SIL: 0.5418 | DB: 1.9464 | WASSER: 6.5425 | MAHA: 9.1765 | OVERLAP: 0.9356
Combo_38 -> V17 / V7 | SIL: 0.6781 | DB: 4.9990 | WASSER: 6.4210 | MAHA: 9.0632 | OVERLAP: 0.9825
Combo_39 -> V17 / V9 | SIL: 0.6207 | DB: 2.5454 | WASSER: 5.3361 | MAHA: 8.2066 | OVERLAP: 0.9663
Combo_40 -> V3 / V16 | SIL: 0.5653 | DB: 1.5658 | WASSER: 4.7064 | MAHA: 6.6325 | OVERLAP: 0.9425
Combo_41 -> V3 / V7 | SIL: 0.6767 | DB: 2.5619 | WASSER: 4.5850 | MAHA: 6.4749 | OVERLAP: 0.9868
Combo_42 -> V3 / V9 | SIL: 0.6378 | DB: 1.4387 | WASSER: 3.5001 | MAHA: 5.2086 | OVERLAP: 0.9778
Combo_43 -> V16 / V7 | SIL: 0.6425 | DB: 5.6302 | WASSER: 4.6446 | MAHA: 6.5370 | OVERLAP: 0.9724
Combo_44 -> V16 / V9 | SIL: 0.3186 | DB: 2.7487 | WASSER: 3.5598 | MAHA: 5.2856 | OVERLAP: 0.7643
Combo_45 -> V7 / V9 | SIL: 0.6449 | DB: 6.3620 | WASSER: 3.4383 | MAHA: 5.0865 | OVERLAP: 0.9751

,Combo,Feature_1,Feature_2,Silhouette,Davies_Bouldin,Wasserstein,Mahalanobis,Overlap_Gaussiano
0,Combo_1,V14,V12,0.544928,1.711897,6.780460,9.615413,0.940298
1,Combo_2,V14,V10,0.634397,2.512369,6.254177,8.964034,0.971761
2,Combo_3,V14,V11,0.405153,4.404303,5.507589,8.184543,0.853600
3,Combo_4,V14,V4,0.423455,3.143184,5.249637,7.962672,0.849717
4,Combo_5,V14,V17,0.610185,1.657416,7.802251,10.718511,0.958545
5,Combo_6,V14,V3,0.526946,2.079137,5.966202,8.641100,0.921435
6,Combo_7,V14,V16,0.459526,4.867179,6.025882,8.687736,0.871774
7,Combo_8,V14,V7,0.653481,4.794604,5.904431,8.568019,0.971352
8,Combo_9,V14,V9,0.426596,2.812050,4.819570,7.656133,0.859266
9,Combo_10,V12,V10,0.469602,1.571416,5.748965,8.164246,0.895896
10,Combo_11,V12,V11,0.462814,1.274879,5.002377,7.299846,0.875753
11,Combo_12,V12,V4,0.416870,1.953813,4.744425,7.050188,0.851575
12,Combo_13,V12,V17,0.513703,1.211282,7.297039,10.059199,0.920643
13,Combo_14,V12,V3,0.489653,1.341428,5.460990,7.808304,0.900533
14,Combo_15,V12,V16,0.435539,1.741815,5.520670,7.859884,0.856196
15,Combo_16,V12,V7,0.553465,1.677241,5.399219,7.727351,0.939368
16,Combo_17,V12,V9,0.463025,1.760734,4.314357,6.702043,0.877912
17,Combo_18,V10,V11,0.661112,1.804725,4.476094,6.417592,0.980743
18,Combo_19,V10,V4,0.454154,3.191389,4.218142,6.132118,0.891058
19,Combo_20,V10,V17,0.665131,3.984565,6.770756,9.438496,0.980795
20,Combo_21,V10,V3,0.683626,1.710167,4.934707,6.990518,0.985322
21,Combo_22,V10,V16,0.650444,2.128338,4.994387,7.048085,0.968221
22,Combo_23,V10,V7,0.698761,4.723654,4.872936,6.899977,0.981484
23,Combo_24,V10,V9,0.479502,3.037099,3.788075,5.728447,0.895602
24,Combo_25,V11,V4,0.339506,1.191371,3.471554,4.922980,0.823505
25,Combo_26,V11,V17,0.611345,1.720193,6.024168,8.701612,0.977742
26,Combo_27,V11,V3,0.331393,1.209326,4.188119,5.958204,0.805307
27,Combo_28,V11,V16,0.342098,1.170757,4.247799,6.025641,0.828901
28,Combo_29,V11,V7,0.638333,10.663796,4.126348,5.851712,0.981256
29,Combo_30,V11,V9,0.336817,1.203827,3.041487,4.409984,0.820656
30,Combo_31,V4,V17,0.540935,1.564460,5.766216,8.493259,0.944539
31,Combo_32,V4,V3,0.290799,1.326432,3.930167,5.649565,0.711582
32,Combo_33,V4,V16,0.328909,5.105762,3.989847,5.720642,0.778837
33,Combo_34,V4,V7,0.623536,3.263770,3.868396,5.537140,0.966934
34,Combo_35,V4,V9,0.349863,12.460382,2.783535,3.983133,0.802901
35,Combo_36,V17,V3,0.639107,1.280722,6.482781,9.132355,0.982211
36,Combo_37,V17,V16,0.541850,1.946436,6.542461,9.176495,0.935626
37,Combo_38,V17,V7,0.678105,4.998971,6.421010,9.063236,0.982504
38,Combo_39,V17,V9,0.620703,2.545358,5.336148,8.206563,0.966322
39,Combo_40,V3,V16,0.565291,1.565809,4.706412,6.632511,0.942467
40,Combo_41,V3,V7,0.676669,2.561939,4.584961,6.474904,0.986795
41,Combo_42,V3,V9,0.637755,1.438691,3.500100,5.208628,0.977775
42,Combo_43,V16,V7,0.642524,5.630193,4.644641,6.537013,0.972420
43,Combo_44,V16,V9,0.318642,2.748741,3.559780,5.285638,0.764292
44,Combo_45,V7,V9,0.644912,6.361965,3.438328,5.086467,0.975126

CSV salvo com sucesso!

### COMBINACAO 3X3

In [5]:

# TARGET

y = df['status_fraude']

# AMOSTRA PARA SILHOUETTE
sample_size_silhouette = 14240
# TOP FEATURES
features_top10 = top10['Feature'].tolist()

# COMBINAÇÕES 3x3
combinacoes_3x3 = list(
    itertools.combinations(features_top10, 3)
)

print(f'Total de combinações: {len(combinacoes_3x3)}\n')

# DICIONÁRIO
dic_combinacoes = {}
# LOOP PRINCIPAL
for i, (f1, f2, f3) in enumerate(combinacoes_3x3, start=1):

    try:
        # MATRIZ
        X = df[[f1, f2, f3]].values

        # PADRONIZAÇÃO
        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(X)


        # GMM
        gmm = GaussianMixture(
            n_components=2,
            covariance_type='diag',
            random_state=42,
            max_iter=100
        )

        gmm.fit(X_scaled)

        labels = gmm.predict(X_scaled)

        # SILHOUETTE (5%)
        sample_size = min(sample_size_silhouette, len(X_scaled))

        idx = np.random.choice(
            len(X_scaled),
            size=sample_size,
            replace=False
        )

        silhouette = silhouette_score(
            X_scaled[idx],
            labels[idx]
        )

      
        # DAVIES-BOULDIN
        davies = davies_bouldin_score(X_scaled, labels)

        # WASSERSTEIN (3 features)
        classe_0 = X_scaled[y == 0]
        classe_1 = X_scaled[y == 1]

        wasser_1 = wasserstein_distance(classe_0[:, 0], classe_1[:, 0])
        wasser_2 = wasserstein_distance(classe_0[:, 1], classe_1[:, 1])
        wasser_3 = wasserstein_distance(classe_0[:, 2], classe_1[:, 2])

        wasser_final = (wasser_1 + wasser_2 + wasser_3) / 3

        # MAHALANOBIS
        media_0 = np.mean(classe_0, axis=0)
        media_1 = np.mean(classe_1, axis=0)

        cov = np.cov(X_scaled.T)
        inv_cov = np.linalg.pinv(cov)

        maha = mahalanobis(media_0, media_1, inv_cov)

        # OVERLAP GAUSSIANO
        probs = gmm.predict_proba(X_scaled)

        overlap = np.mean(np.min(probs, axis=1))
        overlap_score = 1 - overlap

        # SALVAR
        chave = f'Combo3D_{i}'

        dic_combinacoes[chave] = {

            'Feature_1': f1,
            'Feature_2': f2,
            'Feature_3': f3,

            'Silhouette': round(float(silhouette), 6),
            'Davies_Bouldin': round(float(davies), 6),
            'Wasserstein': round(float(wasser_final), 6),
            'Mahalanobis': round(float(maha), 6),
            'Overlap_Gaussiano': round(float(overlap_score), 6)

        }

        # PRINT
        print(
            f'{chave} -> {f1} / {f2} / {f3} '
            f'| SIL: {silhouette:.4f} '
            f'| DB: {davies:.4f} '
            f'| WASSER: {wasser_final:.4f} '
            f'| MAHA: {maha:.4f} '
            f'| OVERLAP: {overlap_score:.4f}'
        )

    except Exception as e:
        print(f'Erro em {f1} / {f2} / {f3}: {e}')

# DATAFRAME FINAL
df_combinacoes = pd.DataFrame.from_dict(
    dic_combinacoes,
    orient='index'
).reset_index()

df_combinacoes.rename(
    columns={'index': 'Combo'},
    inplace=True
)

# EXIBIR

display(df_combinacoes)

# SALVAR CSV
df_combinacoes.to_csv(
    '3x3_visu_metfeat.csv',
    index=False
)

print('\nCSV salvo com sucesso!')

fim = time.time()
print(f"\nTempo total de execução: {fim - inicio:.2f} segundos")

Total de combinações: 120

Combo3D_1 -> V14 / V12 / V10 | SIL: 0.4621 | DB: 2.5252 | WASSER: 6.2612 | MAHA: 10.9422 | OVERLAP: 0.9383
Combo3D_2 -> V14 / V12 / V11 | SIL: 0.4496 | DB: 2.1032 | WASSER: 5.7635 | MAHA: 10.3134 | OVERLAP: 0.9362
Combo3D_3 -> V14 / V12 / V4 | SIL: 0.4114 | DB: 2.4455 | WASSER: 5.5915 | MAHA: 10.1382 | OVERLAP: 0.9116
Combo3D_4 -> V14 / V12 / V17 | SIL: 0.4697 | DB: 1.9935 | WASSER: 7.2932 | MAHA: 12.4203 | OVERLAP: 0.9437
Combo3D_5 -> V14 / V12 / V3 | SIL: 0.4382 | DB: 2.4021 | WASSER: 6.0692 | MAHA: 10.6793 | OVERLAP: 0.9293
Combo3D_6 -> V14 / V12 / V16 | SIL: 0.4110 | DB: 2.5010 | WASSER: 6.1090 | MAHA: 10.7171 | OVERLAP: 0.9183
Combo3D_7 -> V14 / V12 / V7 | SIL: 0.4911 | DB: 2.5347 | WASSER: 6.0280 | MAHA: 10.6202 | OVERLAP: 0.9556
Combo3D_8 -> V14 / V12 / V9 | SIL: 0.4574 | DB: 2.1704 | WASSER: 5.3048 | MAHA: 9.8992 | OVERLAP: 0.9349
Combo3D_9 -> V14 / V10 / V11 | SIL: 0.5577 | DB: 2.8751 | WASSER: 5.4126 | MAHA: 9.7089 | OVERLAP: 0.9743
Combo3D_10 -> V14 / V10 / V4 | SIL: 0.5166 | DB: 3.1809 | WASSER: 5.2407 | MAHA: 9.5226 | OVERLAP: 0.9498
Combo3D_11 -> V14 / V10 / V17 | SIL: 0.6144 | DB: 2.6050 | WASSER: 6.9424 | MAHA: 11.9232 | OVERLAP: 0.9800
Combo3D_12 -> V14 / V10 / V3 | SIL: 0.6020 | DB: 2.2476 | WASSER: 5.7184 | MAHA: 10.0968 | OVERLAP: 0.9804
Combo3D_13 -> V14 / V10 / V16 | SIL: 0.5752 | DB: 3.0218 | WASSER: 5.7581 | MAHA: 10.1367 | OVERLAP: 0.9742
Combo3D_14 -> V14 / V10 / V7 | SIL: 0.6355 | DB: 4.7704 | WASSER: 5.6772 | MAHA: 10.0343 | OVERLAP: 0.9837
Combo3D_15 -> V14 / V10 / V9 | SIL: 0.5608 | DB: 3.1635 | WASSER: 4.9539 | MAHA: 9.2678 | OVERLAP: 0.9651
Combo3D_16 -> V14 / V11 / V4 | SIL: 0.3793 | DB: 3.4799 | WASSER: 4.7429 | MAHA: 8.7928 | OVERLAP: 0.8856
Combo3D_17 -> V14 / V11 / V17 | SIL: 0.5274 | DB: 2.1559 | WASSER: 6.4447 | MAHA: 11.3488 | OVERLAP: 0.9607
Combo3D_18 -> V14 / V11 / V3 | SIL: 0.4772 | DB: 2.5366 | WASSER: 5.2206 | MAHA: 9.4116 | OVERLAP: 0.9441
Combo3D_19 -> V14 / V11 / V16 | SIL: 0.3984 | DB: 4.9569 | WASSER: 5.2604 | MAHA: 9.4544 | OVERLAP: 0.9082
Combo3D_20 -> V14 / V11 / V7 | SIL: 0.5591 | DB: 5.4887 | WASSER: 5.1795 | MAHA: 9.3445 | OVERLAP: 0.9730
Combo3D_21 -> V14 / V11 / V9 | SIL: 0.3805 | DB: 3.0427 | WASSER: 4.4562 | MAHA: 8.5162 | OVERLAP: 0.9020
Combo3D_22 -> V14 / V4 / V17 | SIL: 0.5070 | DB: 2.2748 | WASSER: 6.2727 | MAHA: 11.1899 | OVERLAP: 0.9509
Combo3D_23 -> V14 / V4 / V3 | SIL: 0.4679 | DB: 2.6366 | WASSER: 5.0487 | MAHA: 9.2193 | OVERLAP: 0.9349
Combo3D_24 -> V14 / V4 / V16 | SIL: 0.3809 | DB: 5.1100 | WASSER: 5.0885 | MAHA: 9.2630 | OVERLAP: 0.8761
Combo3D_25 -> V14 / V4 / V7 | SIL: 0.5564 | DB: 4.4422 | WASSER: 5.0075 | MAHA: 9.1508 | OVERLAP: 0.9714
Combo3D_26 -> V14 / V4 / V9 | SIL: 0.2878 | DB: 10.7289 | WASSER: 4.2842 | MAHA: 8.3032 | OVERLAP: 0.8431
Combo3D_27 -> V14 / V17 / V3 | SIL: 0.5798 | DB: 1.7285 | WASSER: 6.7504 | MAHA: 11.6824 | OVERLAP: 0.9772
Combo3D_28 -> V14 / V17 / V16 | SIL: 0.5172 | DB: 2.2252 | WASSER: 6.7902 | MAHA: 11.7169 | OVERLAP: 0.9577
Combo3D_29 -> V14 / V17 / V7 | SIL: 0.6035 | DB: 3.0741 | WASSER: 6.7092 | MAHA: 11.6284 | OVERLAP: 0.9783
Combo3D_30 -> V14 / V17 / V9 | SIL: 0.4665 | DB: 2.5246 | WASSER: 5.9860 | MAHA: 10.9738 | OVERLAP: 0.9342
Combo3D_31 -> V14 / V3 / V16 | SIL: 0.4925 | DB: 2.5222 | WASSER: 5.5662 | MAHA: 9.8523 | OVERLAP: 0.9504
Combo3D_32 -> V14 / V3 / V7 | SIL: 0.5827 | DB: 2.7592 | WASSER: 5.4852 | MAHA: 9.7469 | OVERLAP: 0.9789
Combo3D_33 -> V14 / V3 / V9 | SIL: 0.4062 | DB: 3.0741 | WASSER: 4.7620 | MAHA: 8.9559 | OVERLAP: 0.9091
Combo3D_34 -> V14 / V16 / V7 | SIL: 0.5502 | DB: 5.3569 | WASSER: 5.5250 | MAHA: 9.7883 | OVERLAP: 0.9710
Combo3D_35 -> V14 / V16 / V9 | SIL: 0.3804 | DB: 4.2913 | WASSER: 4.8017 | MAHA: 9.0009 | OVERLAP: 0.8880
Combo3D_36 -> V14 / V7 / V9 | SIL: 0.5523 | DB: 5.2458 | WASSER: 4.7208 | MAHA: 8.8854 | OVERLAP: 0.9657
Combo3D_37 -> V12 / V10 / V11 | SIL: 0.4015 | DB: 1.9949 | WASSER: 5.0758 | MAHA: 8.9757 | OVERLAP: 0.9146
Combo3D_38 -> V12 / V10 / V4 | SIL: 0.3667 | DB: 2.4280 | WASSER: 4.9038 | MAHA: 8.7739 | OVERLAP: 0.9047
Combo3D_39 -> V12 / V10 / V17 | SIL: 0.4543 | DB: 2.0018 | WASSER: 6.6056 | MAHA: 11.3342 | OVERLAP: 0.9343
Combo3D_40 -> V12 / V10 / V3 | SIL: 0.4444 | DB: 2.0707 | WASSER: 5.3816 | MAHA: 9.3939 | OVERLAP: 0.9323
Combo3D_41 -> V12 / V10 / V16 | SIL: 0.3545 | DB: 2.2962 | WASSER: 5.4213 | MAHA: 9.4368 | OVERLAP: 0.8860
Combo3D_42 -> V12 / V10 / V7 | SIL: 0.4786 | DB: 2.5795 | WASSER: 5.3404 | MAHA: 9.3268 | OVERLAP: 0.9471
Combo3D_43 -> V12 / V10 / V9 | SIL: 0.4538 | DB: 2.1359 | WASSER: 4.6171 | MAHA: 8.4967 | OVERLAP: 0.9366
Combo3D_44 -> V12 / V11 / V4 | SIL: 0.3562 | DB: 2.3268 | WASSER: 4.4061 | MAHA: 7.9759 | OVERLAP: 0.8742
Combo3D_45 -> V12 / V11 / V17 | SIL: 0.4369 | DB: 1.5368 | WASSER: 6.1079 | MAHA: 10.7283 | OVERLAP: 0.9349
Combo3D_46 -> V12 / V11 / V3 | SIL: 0.4131 | DB: 1.6847 | WASSER: 4.8838 | MAHA: 8.6533 | OVERLAP: 0.9182
Combo3D_47 -> V12 / V11 / V16 | SIL: 0.3567 | DB: 2.2964 | WASSER: 4.9236 | MAHA: 8.6998 | OVERLAP: 0.8671
Combo3D_48 -> V12 / V11 / V7 | SIL: 0.4523 | DB: 2.0341 | WASSER: 4.8426 | MAHA: 8.5803 | OVERLAP: 0.9456
Combo3D_49 -> V12 / V11 / V9 | SIL: 0.4072 | DB: 1.9933 | WASSER: 4.1194 | MAHA: 7.6698 | OVERLAP: 0.9013
Combo3D_50 -> V12 / V4 / V17 | SIL: 0.4019 | DB: 1.9352 | WASSER: 5.9359 | MAHA: 10.5600 | OVERLAP: 0.9124
Combo3D_51 -> V12 / V4 / V3 | SIL: 0.3509 | DB: 2.5016 | WASSER: 4.7119 | MAHA: 8.4437 | OVERLAP: 0.8705
Combo3D_52 -> V12 / V4 / V16 | SIL: 0.3164 | DB: 2.7987 | WASSER: 4.7516 | MAHA: 8.4914 | OVERLAP: 0.8587
Combo3D_53 -> V12 / V4 / V7 | SIL: 0.4263 | DB: 2.3213 | WASSER: 4.6707 | MAHA: 8.3689 | OVERLAP: 0.9269
Combo3D_54 -> V12 / V4 / V9 | SIL: 0.3377 | DB: 2.9597 | WASSER: 3.9474 | MAHA: 7.4326 | OVERLAP: 0.8840
Combo3D_55 -> V12 / V17 / V3 | SIL: 0.4519 | DB: 1.6874 | WASSER: 6.4136 | MAHA: 11.0805 | OVERLAP: 0.9412
Combo3D_56 -> V12 / V17 / V16 | SIL: 0.3985 | DB: 1.9325 | WASSER: 6.4534 | MAHA: 11.1170 | OVERLAP: 0.9043
Combo3D_57 -> V12 / V17 / V7 | SIL: 0.5093 | DB: 2.1062 | WASSER: 6.3724 | MAHA: 11.0236 | OVERLAP: 0.9557
Combo3D_58 -> V12 / V17 / V9 | SIL: 0.4383 | DB: 1.8053 | WASSER: 5.6492 | MAHA: 10.3308 | OVERLAP: 0.9252
Combo3D_59 -> V12 / V3 / V16 | SIL: 0.3738 | DB: 2.3118 | WASSER: 5.2294 | MAHA: 9.1307 | OVERLAP: 0.8839
Combo3D_60 -> V12 / V3 / V7 | SIL: 0.5202 | DB: 2.4666 | WASSER: 5.1484 | MAHA: 9.0168 | OVERLAP: 0.9615
Combo3D_61 -> V12 / V3 / V9 | SIL: 0.4257 | DB: 1.8991 | WASSER: 4.4251 | MAHA: 8.1553 | OVERLAP: 0.9191
Combo3D_62 -> V12 / V16 / V7 | SIL: 0.4462 | DB: 2.4413 | WASSER: 5.1882 | MAHA: 9.0615 | OVERLAP: 0.9345
Combo3D_63 -> V12 / V16 / V9 | SIL: 0.3458 | DB: 2.6488 | WASSER: 4.4649 | MAHA: 8.2047 | OVERLAP: 0.8706
Combo3D_64 -> V12 / V7 / V9 | SIL: 0.4695 | DB: 2.1358 | WASSER: 4.3840 | MAHA: 8.0778 | OVERLAP: 0.9387
Combo3D_65 -> V10 / V11 / V4 | SIL: 0.3257 | DB: 4.1443 | WASSER: 4.0553 | MAHA: 7.1772 | OVERLAP: 0.8840
Combo3D_66 -> V10 / V11 / V17 | SIL: 0.5841 | DB: 3.5523 | WASSER: 5.7570 | MAHA: 10.1486 | OVERLAP: 0.9841
Combo3D_67 -> V10 / V11 / V3 | SIL: 0.5967 | DB: 1.9180 | WASSER: 4.5330 | MAHA: 7.9232 | OVERLAP: 0.9892
Combo3D_68 -> V10 / V11 / V16 | SIL: 0.5943 | DB: 2.3292 | WASSER: 4.5728 | MAHA: 7.9740 | OVERLAP: 0.9791
Combo3D_69 -> V10 / V11 / V7 | SIL: 0.6013 | DB: 5.1738 | WASSER: 4.4918 | MAHA: 7.8434 | OVERLAP: 0.9838
Combo3D_70 -> V10 / V11 / V9 | SIL: 0.5933 | DB: 2.1082 | WASSER: 3.7686 | MAHA: 6.8355 | OVERLAP: 0.9779
Combo3D_71 -> V10 / V4 / V17 | SIL: 0.5290 | DB: 3.1681 | WASSER: 5.5850 | MAHA: 9.9705 | OVERLAP: 0.9607
Combo3D_72 -> V10 / V4 / V3 | SIL: 0.5212 | DB: 2.6679 | WASSER: 4.3610 | MAHA: 7.6938 | OVERLAP: 0.9521
Combo3D_73 -> V10 / V4 / V16 | SIL: 0.3027 | DB: 3.5891 | WASSER: 4.4008 | MAHA: 7.7461 | OVERLAP: 0.8778
Combo3D_74 -> V10 / V4 / V7 | SIL: 0.5330 | DB: 3.8070 | WASSER: 4.3198 | MAHA: 7.6116 | OVERLAP: 0.9567
Combo3D_75 -> V10 / V4 / V9 | SIL: 0.4197 | DB: 3.6387 | WASSER: 3.5966 | MAHA: 6.5682 | OVERLAP: 0.9199
Combo3D_76 -> V10 / V17 / V3 | SIL: 0.6224 | DB: 2.4324 | WASSER: 6.0627 | MAHA: 10.5203 | OVERLAP: 0.9860
Combo3D_77 -> V10 / V17 / V16 | SIL: 0.5762 | DB: 4.0142 | WASSER: 6.1025 | MAHA: 10.5586 | OVERLAP: 0.9772
Combo3D_78 -> V10 / V17 / V7 | SIL: 0.6182 | DB: 6.8803 | WASSER: 6.0216 | MAHA: 10.4603 | OVERLAP: 0.9842
Combo3D_79 -> V10 / V17 / V9 | SIL: 0.6064 | DB: 3.5303 | WASSER: 5.2983 | MAHA: 9.7275 | OVERLAP: 0.9800
Combo3D_80 -> V10 / V3 / V16 | SIL: 0.5830 | DB: 2.1179 | WASSER: 4.8785 | MAHA: 8.4420 | OVERLAP: 0.9824
Combo3D_81 -> V10 / V3 / V7 | SIL: 0.6424 | DB: 3.1665 | WASSER: 4.7975 | MAHA: 8.3187 | OVERLAP: 0.9877
Combo3D_82 -> V10 / V3 / V9 | SIL: 0.6411 | DB: 1.9007 | WASSER: 4.0743 | MAHA: 7.3761 | OVERLAP: 0.9901
Combo3D_83 -> V10 / V16 / V7 | SIL: 0.6076 | DB: 5.2219 | WASSER: 4.8373 | MAHA: 8.3671 | OVERLAP: 0.9812
Combo3D_84 -> V10 / V16 / V9 | SIL: 0.3761 | DB: 2.5504 | WASSER: 4.1141 | MAHA: 7.4306 | OVERLAP: 0.8909
Combo3D_85 -> V10 / V7 / V9 | SIL: 0.6434 | DB: 4.1134 | WASSER: 4.0331 | MAHA: 7.2903 | OVERLAP: 0.9851
Combo3D_86 -> V11 / V4 / V17 | SIL: 0.4691 | DB: 1.9319 | WASSER: 5.0873 | MAHA: 9.2760 | OVERLAP: 0.9582
Combo3D_87 -> V11 / V4 / V3 | SIL: 0.2312 | DB: 1.6662 | WASSER: 3.8633 | MAHA: 6.7695 | OVERLAP: 0.7998
Combo3D_88 -> V11 / V4 / V16 | SIL: 0.2372 | DB: 1.6132 | WASSER: 3.9031 | MAHA: 6.8290 | OVERLAP: 0.8265
Combo3D_89 -> V11 / V4 / V7 | SIL: 0.5291 | DB: 3.6931 | WASSER: 3.8221 | MAHA: 6.6760 | OVERLAP: 0.9720
Combo3D_90 -> V11 / V4 / V9 | SIL: 0.2354 | DB: 1.6195 | WASSER: 3.0989 | MAHA: 5.4566 | OVERLAP: 0.8237
Combo3D_91 -> V11 / V17 / V3 | SIL: 0.6118 | DB: 1.5596 | WASSER: 5.5650 | MAHA: 9.8645 | OVERLAP: 0.9873
Combo3D_92 -> V11 / V17 / V16 | SIL: 0.4719 | DB: 2.1989 | WASSER: 5.6048 | MAHA: 9.9054 | OVERLAP: 0.9611
Combo3D_93 -> V11 / V17 / V7 | SIL: 0.6002 | DB: 5.1816 | WASSER: 5.5238 | MAHA: 9.8006 | OVERLAP: 0.9850
Combo3D_94 -> V11 / V17 / V9 | SIL: 0.5417 | DB: 2.4087 | WASSER: 4.8006 | MAHA: 9.0143 | OVERLAP: 0.9739
Combo3D_95 -> V11 / V3 / V16 | SIL: 0.5544 | DB: 1.7856 | WASSER: 4.3808 | MAHA: 7.6092 | OVERLAP: 0.9798
Combo3D_96 -> V11 / V3 / V7 | SIL: 0.5888 | DB: 2.9238 | WASSER: 4.2998 | MAHA: 7.4722 | OVERLAP: 0.9889
Combo3D_97 -> V11 / V3 / V9 | SIL: 0.6001 | DB: 1.6274 | WASSER: 3.5766 | MAHA: 6.4062 | OVERLAP: 0.9882
Combo3D_98 -> V11 / V16 / V7 | SIL: 0.5699 | DB: 6.8971 | WASSER: 4.3396 | MAHA: 7.5261 | OVERLAP: 0.9787
Combo3D_99 -> V11 / V16 / V9 | SIL: 0.2442 | DB: 3.9515 | WASSER: 3.6164 | MAHA: 6.4689 | OVERLAP: 0.7756
Combo3D_100 -> V11 / V7 / V9 | SIL: 0.5649 | DB: 6.5755 | WASSER: 3.5354 | MAHA: 6.3072 | OVERLAP: 0.9796
Combo3D_101 -> V4 / V17 / V3 | SIL: 0.5578 | DB: 1.9059 | WASSER: 5.3931 | MAHA: 9.6812 | OVERLAP: 0.9707
Combo3D_102 -> V4 / V17 / V16 | SIL: 0.4410 | DB: 2.8400 | WASSER: 5.4328 | MAHA: 9.7229 | OVERLAP: 0.9253
Combo3D_103 -> V4 / V17 / V7 | SIL: 0.5726 | DB: 3.8474 | WASSER: 5.3519 | MAHA: 9.6161 | OVERLAP: 0.9795
Combo3D_104 -> V4 / V17 / V9 | SIL: 0.3943 | DB: 4.6963 | WASSER: 4.6286 | MAHA: 8.8133 | OVERLAP: 0.8897
Combo3D_105 -> V4 / V3 / V16 | SIL: 0.3473 | DB: 4.7790 | WASSER: 4.2088 | MAHA: 7.3700 | OVERLAP: 0.8490
Combo3D_106 -> V4 / V3 / V7 | SIL: 0.6036 | DB: 3.0203 | WASSER: 4.1278 | MAHA: 7.2285 | OVERLAP: 0.9841
Combo3D_107 -> V4 / V3 / V9 | SIL: 0.3116 | DB: 12.6138 | WASSER: 3.4046 | MAHA: 6.1202 | OVERLAP: 0.8382
Combo3D_108 -> V4 / V16 / V7 | SIL: 0.5599 | DB: 6.1271 | WASSER: 4.1676 | MAHA: 7.2842 | OVERLAP: 0.9678
Combo3D_109 -> V4 / V16 / V9 | SIL: 0.1925 | DB: 5.5545 | WASSER: 3.4444 | MAHA: 6.1858 | OVERLAP: 0.8245
Combo3D_110 -> V4 / V7 / V9 | SIL: 0.5341 | DB: 7.3345 | WASSER: 3.3634 | MAHA: 6.0165 | OVERLAP: 0.9541
Combo3D_111 -> V17 / V3 / V16 | SIL: 0.5226 | DB: 1.9514 | WASSER: 5.9106 | MAHA: 10.2859 | OVERLAP: 0.9710
Combo3D_112 -> V17 / V3 / V7 | SIL: 0.6300 | DB: 2.5849 | WASSER: 5.8296 | MAHA: 10.1850 | OVERLAP: 0.9865
Combo3D_113 -> V17 / V3 / V9 | SIL: 0.6042 | DB: 1.9504 | WASSER: 5.1063 | MAHA: 9.4307 | OVERLAP: 0.9837
Combo3D_114 -> V17 / V16 / V7 | SIL: 0.5948 | DB: 4.8683 | WASSER: 5.8694 | MAHA: 10.2246 | OVERLAP: 0.9786
Combo3D_115 -> V17 / V16 / V9 | SIL: 0.4718 | DB: 2.5337 | WASSER: 5.1461 | MAHA: 9.4735 | OVERLAP: 0.9412
Combo3D_116 -> V17 / V7 / V9 | SIL: 0.6087 | DB: 6.4465 | WASSER: 5.0652 | MAHA: 9.3638 | OVERLAP: 0.9822
Combo3D_117 -> V3 / V16 / V7 | SIL: 0.6003 | DB: 3.1421 | WASSER: 4.6453 | MAHA: 8.0202 | OVERLAP: 0.9837
Combo3D_118 -> V3 / V16 / V9 | SIL: 0.5336 | DB: 2.1400 | WASSER: 3.9221 | MAHA: 7.0377 | OVERLAP: 0.9703
Combo3D_119 -> V3 / V7 / V9 | SIL: 0.5995 | DB: 3.1224 | WASSER: 3.8411 | MAHA: 6.8894 | OVERLAP: 0.9871
Combo3D_120 -> V16 / V7 / V9 | SIL: 0.5680 | DB: 6.0397 | WASSER: 3.8809 | MAHA: 6.9478 | OVERLAP: 0.9743

,Combo,Feature_1,Feature_2,Feature_3,Silhouette,Davies_Bouldin,Wasserstein,Mahalanobis,Overlap_Gaussiano
0,Combo3D_1,V14,V12,V10,0.462069,2.525182,6.261201,10.942234,0.938298
1,Combo3D_2,V14,V12,V11,0.449584,2.103152,5.763475,10.313357,0.936230
2,Combo3D_3,V14,V12,V4,0.411392,2.445530,5.591507,10.138182,0.911582
3,Combo3D_4,V14,V12,V17,0.469655,1.993484,7.293250,12.420349,0.943746
4,Combo3D_5,V14,V12,V3,0.438152,2.402055,6.069217,10.679288,0.929349
...,...,...,...,...,...,...,...,...,...
115,Combo3D_116,V17,V7,V9,0.608653,6.446502,5.065162,9.363815,0.982240
116,Combo3D_117,V3,V16,V7,0.600253,3.142120,4.645338,8.020197,0.983733
117,Combo3D_118,V3,V16,V9,0.533636,2.140000,3.922097,7.037684,0.970332
118,Combo3D_119,V3,V7,V9,0.599462,3.122408,3.841130,6.889352,0.987117
119,Combo3D_120,V16,V7,V9,0.567992,6.039725,3.880916,6.947757,0.974323

CSV salvo com sucesso!

Tempo total de execução: 1050.71 segundos